// قاعدة بيانات مطارات عالمية شاملة (كود IATA + المدينة عربي/إنجليزي + الدولة عربي/إنجليزي).
// تغطي كل دول آسيا وأفريقيا بمطاراتها الرئيسية + وجهات أوروبا والأمريكتين وأوقيانوسيا الرئيسية.
// [iata, cityAr, cityEn, countryAr, countryEn]
const RAW = [
  // ===== السعودية =====
  ["RUH", "الرياض", "Riyadh", "السعودية", "Saudi Arabia"],
  ["JED", "جدة", "Jeddah", "السعودية", "Saudi Arabia"],
  ["DMM", "الدمام", "Dammam", "السعودية", "Saudi Arabia"],
  ["MED", "المدينة المنورة", "Medina", "السعودية", "Saudi Arabia"],
  ["AHB", "أبها", "Abha", "السعودية", "Saudi Arabia"],
  ["TUU", "تبوك", "Tabuk", "السعودية", "Saudi Arabia"],
  ["TIF", "الطائف", "Taif", "السعودية", "Saudi Arabia"],
  ["HAS", "حائل", "Hail", "السعودية", "Saudi Arabia"],
  ["ELQ", "القصيم", "Gassim", "السعودية", "Saudi Arabia"],
  ["EAM", "نجران", "Najran", "السعودية", "Saudi Arabia"],
  ["YNB", "ينبع", "Yanbu", "السعودية", "Saudi Arabia"],
  ["ABT", "الباحة", "Al Baha", "السعودية", "Saudi Arabia"],
  ["HBT", "حفر الباطن", "Hafr Albatin", "السعودية", "Saudi Arabia"],
  ["RAE", "عرعر", "Arar", "السعودية", "Saudi Arabia"],
  ["GIZ", "جازان", "Jazan", "السعودية", "Saudi Arabia"],
  ["AJF", "الجوف", "Al Jouf", "السعودية", "Saudi Arabia"],

  // ===== اليمن =====
  ["SAH", "صنعاء", "Sanaa", "اليمن", "Yemen"],
  ["ADE", "عدن", "Aden", "اليمن", "Yemen"],
  ["HOD", "الحديدة", "Hodeidah", "اليمن", "Yemen"],
  ["RIY", "المكلا", "Mukalla", "اليمن", "Yemen"],
  ["SAY", "سيئون", "Seiyun", "اليمن", "Yemen"],

  // ===== الخليج =====
  ["DXB", "دبي", "Dubai", "الإمارات", "UAE"],
  ["AUH", "أبوظبي", "Abu Dhabi", "الإمارات", "UAE"],
  ["SHJ", "الشارقة", "Sharjah", "الإمارات", "UAE"],
  ["FJR", "الفجيرة", "Fujairah", "الإمارات", "UAE"],
  ["RKT", "رأس الخيمة", "Ras Al Khaimah", "الإمارات", "UAE"],
  ["KWI", "الكويت", "Kuwait", "الكويت", "Kuwait"],
  ["BAH", "المنامة", "Manama", "البحرين", "Bahrain"],
  ["DOH", "الدوحة", "Doha", "قطر", "Qatar"],
  ["MCT", "مسقط", "Muscat", "عُمان", "Oman"],
  ["SLL", "صلالة", "Salalah", "عُمان", "Oman"],

  // ===== الشرق الأوسط =====
  ["CAI", "القاهرة", "Cairo", "مصر", "Egypt"],
  ["HBE", "الإسكندرية", "Alexandria", "مصر", "Egypt"],
  ["LXR", "الأقصر", "Luxor", "مصر", "Egypt"],
  ["ASW", "أسوان", "Aswan", "مصر", "Egypt"],
  ["SSH", "شرم الشيخ", "Sharm El Sheikh", "مصر", "Egypt"],
  ["HRG", "الغردقة", "Hurghada", "مصر", "Egypt"],
  ["RMF", "مرسى علم", "Marsa Alam", "مصر", "Egypt"],
  ["HMB", "سوهاج", "Sohag", "مصر", "Egypt"],
  ["ATZ", "أسيوط", "Assiut", "مصر", "Egypt"],
  ["BEY", "بيروت", "Beirut", "لبنان", "Lebanon"],
  ["AMM", "عمان", "Amman", "الأردن", "Jordan"],
  ["AQJ", "العقبة", "Aqaba", "الأردن", "Jordan"],
  ["DAM", "دمشق", "Damascus", "سوريا", "Syria"],
  ["ALP", "حلب", "Aleppo", "سوريا", "Syria"],
  ["LTK", "اللاذقية", "Latakia", "سوريا", "Syria"],
  ["BGW", "بغداد", "Baghdad", "العراق", "Iraq"],
  ["EBL", "أربيل", "Erbil", "العراق", "Iraq"],
  ["BSR", "البصرة", "Basra", "العراق", "Iraq"],
  ["NJF", "النجف", "Najaf", "العراق", "Iraq"],
  ["ISU", "السليمانية", "Sulaymaniyah", "العراق", "Iraq"],
  ["IKA", "طهران", "Tehran", "إيران", "Iran"],
  ["MHD", "مشهد", "Mashhad", "إيران", "Iran"],
  ["SYZ", "شيراز", "Shiraz", "إيران", "Iran"],
  ["IFN", "أصفهان", "Isfahan", "إيران", "Iran"],
  ["TBZ", "تبريز", "Tabriz", "إيران", "Iran"],
  ["TLV", "تل أبيب", "Tel Aviv", "فلسطين", "Palestine"],
  ["IST", "إسطنبول", "Istanbul", "تركيا", "Turkey"],
  ["SAW", "إسطنبول (ساو)", "Istanbul SAW", "تركيا", "Turkey"],
  ["AYT", "أنطاليا", "Antalya", "تركيا", "Turkey"],
  ["ESB", "أنقرة", "Ankara", "تركيا", "Turkey"],
  ["ADA", "أضنة", "Adana", "تركيا", "Turkey"],
  ["GZP", "ألانيا", "Alanya", "تركيا", "Turkey"],
  ["DIY", "ديار بكر", "Diyarbakir", "تركيا", "Turkey"],
  ["TZX", "طرابزون", "Trabzon", "تركيا", "Turkey"],

  // ===== آسيا الوسطى + القوقاز + أفغانستان =====
  ["ALA", "ألماتي", "Almaty", "كازاخستان", "Kazakhstan"],
  ["NQZ", "أستانة", "Astana", "كازاخستان", "Kazakhstan"],
  ["CIT", "شيمكنت", "Shymkent", "كازاخستان", "Kazakhstan"],
  ["TAS", "طشقند", "Tashkent", "أوزبكستان", "Uzbekistan"],
  ["SKD", "سمرقند", "Samarkand", "أوزبكستان", "Uzbekistan"],
  ["FRU", "بشكيك", "Bishkek", "قيرغيزستان", "Kyrgyzstan"],
  ["OSS", "أوش", "Osh", "قيرغيزستان", "Kyrgyzstan"],
  ["DYU", "دوشنبه", "Dushanbe", "طاجيكستان", "Tajikistan"],
  ["ASB", "عشق آباد", "Ashgabat", "تركمانستان", "Turkmenistan"],
  ["KBL", "كابل", "Kabul", "أفغانستان", "Afghanistan"],
  ["GYD", "باكو", "Baku", "أذربيجان", "Azerbaijan"],
  ["EVN", "يريفان", "Yerevan", "أرمينيا", "Armenia"],
  ["TBS", "تبليسي", "Tbilisi", "جورجيا", "Georgia"],

  // ===== جنوب آسيا =====
  ["DEL", "نيودلهي", "Delhi", "الهند", "India"],
  ["BOM", "مومباي", "Mumbai", "الهند", "India"],
  ["MAA", "تشيناي", "Chennai", "الهند", "India"],
  ["HYD", "حيدر أباد", "Hyderabad", "الهند", "India"],
  ["CCJ", "كاليكوت", "Calicut", "الهند", "India"],
  ["BLR", "بنغالور", "Bengaluru", "الهند", "India"],
  ["COK", "كوتشين", "Kochi", "الهند", "India"],
  ["TRV", "تريفاندرم", "Trivandrum", "الهند", "India"],
  ["AMD", "أحمد آباد", "Ahmedabad", "الهند", "India"],
  ["CCU", "كلكتا", "Kolkata", "الهند", "India"],
  ["GOI", "غوا", "Goa", "الهند", "India"],
  ["LKO", "لكنؤ", "Lucknow", "الهند", "India"],
  ["JAI", "جايبور", "Jaipur", "الهند", "India"],
  ["NAG", "ناغبور", "Nagpur", "الهند", "India"],
  ["CJB", "كويمباتور", "Coimbatore", "الهند", "India"],
  ["ATQ", "أمرتسار", "Amritsar", "الهند", "India"],
  ["PAT", "بتنا", "Patna", "الهند", "India"],
  ["VNS", "واراناسي", "Varanasi", "الهند", "India"],
  ["GAU", "غواهاتي", "Guwahati", "الهند", "India"],
  ["IXC", "شانديغار", "Chandigarh", "الهند", "India"],
  ["IXM", "مادوراي", "Madurai", "الهند", "India"],
  ["IXE", "مانغلور", "Mangalore", "الهند", "India"],
  ["IXR", "رانشي", "Ranchi", "الهند", "India"],
  ["ISB", "إسلام آباد", "Islamabad", "باكستان", "Pakistan"],
  ["KHI", "كراتشي", "Karachi", "باكستان", "Pakistan"],
  ["LHE", "لاهور", "Lahore", "باكستان", "Pakistan"],
  ["MUX", "ملتان", "Multan", "باكستان", "Pakistan"],
  ["PEW", "بيشاور", "Peshawar", "باكستان", "Pakistan"],
  ["SKT", "سيالكوت", "Sialkot", "باكستان", "Pakistan"],
  ["LYP", "فيصل آباد", "Faisalabad", "باكستان", "Pakistan"],
  ["DAC", "دكا", "Dhaka", "بنغلاديش", "Bangladesh"],
  ["CGP", "شيتاغونغ", "Chittagong", "بنغلاديش", "Bangladesh"],
  ["ZYL", "سلهت", "Sylhet", "بنغلاديش", "Bangladesh"],
  ["CXB", "كوكس بازار", "Coxs Bazar", "بنغلاديش", "Bangladesh"],
  ["KTM", "كاتماندو", "Kathmandu", "نيبال", "Nepal"],
  ["PKR", "بوخارا", "Pokhara", "نيبال", "Nepal"],
  ["BWA", "بهيراهوا", "Bhairahawa", "نيبال", "Nepal"],
  ["CMB", "كولومبو", "Colombo", "سريلانكا", "Sri Lanka"],
  ["JAF", "جافنا", "Jaffna", "سريلانكا", "Sri Lanka"],
  ["MLE", "ماليه", "Male", "المالديف", "Maldives"],
  ["PBH", "بارو", "Paro", "بوتان", "Bhutan"],

  // ===== جنوب شرق آسيا =====
  ["BKK", "بانكوك", "Bangkok", "تايلاند", "Thailand"],
  ["HKT", "بوكيت", "Phuket", "تايلاند", "Thailand"],
  ["CNX", "شيانغ ماي", "Chiang Mai", "تايلاند", "Thailand"],
  ["KBV", "كرابي", "Krabi", "تايلاند", "Thailand"],
  ["USM", "كو ساموي", "Koh Samui", "تايلاند", "Thailand"],
  ["HDY", "هات ياي", "Hat Yai", "تايلاند", "Thailand"],
  ["UTH", "أودون تاني", "Udon Thani", "تايلاند", "Thailand"],
  ["SIN", "سنغافورة", "Singapore", "سنغافورة", "Singapore"],
  ["KUL", "كوالالمبور", "Kuala Lumpur", "ماليزيا", "Malaysia"],
  ["PEN", "بينانج", "Penang", "ماليزيا", "Malaysia"],
  ["BKI", "كوتا كينابالو", "Kota Kinabalu", "ماليزيا", "Malaysia"],
  ["KCH", "كوتشينغ", "Kuching", "ماليزيا", "Malaysia"],
  ["LGK", "لانكاوي", "Langkawi", "ماليزيا", "Malaysia"],
  ["JHB", "جوهور باهرو", "Johor Bahru", "ماليزيا", "Malaysia"],
  ["MNL", "مانيلا", "Manila", "الفلبين", "Philippines"],
  ["CEB", "سيبو", "Cebu", "الفلبين", "Philippines"],
  ["DVO", "دافاو", "Davao", "الفلبين", "Philippines"],
  ["KLO", "كاليبو", "Kalibo", "الفلبين", "Philippines"],
  ["CGY", "كاغايان دي أورو", "Cagayan de Oro", "الفلبين", "Philippines"],
  ["PPS", "بورتو برنسيسا", "Puerto Princesa", "الفلبين", "Philippines"],
  ["CRK", "كلارك", "Clark", "الفلبين", "Philippines"],
  ["CGK", "جاكرتا", "Jakarta", "إندونيسيا", "Indonesia"],
  ["DPS", "بالي", "Bali", "إندونيسيا", "Indonesia"],
  ["SUB", "سورابايا", "Surabaya", "إندونيسيا", "Indonesia"],
  ["KNO", "ميدان", "Medan", "إندونيسيا", "Indonesia"],
  ["UPG", "ماكاسار", "Makassar", "إندونيسيا", "Indonesia"],
  ["BPN", "باليكبابان", "Balikpapan", "إندونيسيا", "Indonesia"],
  ["LOP", "لومبوك", "Lombok", "إندونيسيا", "Indonesia"],
  ["JOG", "يوغياكارتا", "Yogyakarta", "إندونيسيا", "Indonesia"],
  ["HAN", "هانوي", "Hanoi", "فيتنام", "Vietnam"],
  ["SGN", "هو تشي منه", "Ho Chi Minh", "فيتنام", "Vietnam"],
  ["DAD", "دا نانغ", "Da Nang", "فيتنام", "Vietnam"],
  ["CXR", "نها ترانغ", "Nha Trang", "فيتنام", "Vietnam"],
  ["PQC", "فو كوك", "Phu Quoc", "فيتنام", "Vietnam"],
  ["PNH", "بنوم بنه", "Phnom Penh", "كمبوديا", "Cambodia"],
  ["REP", "سيام ريب", "Siem Reap", "كمبوديا", "Cambodia"],
  ["VTE", "فيانتيان", "Vientiane", "لاوس", "Laos"],
  ["LPQ", "لوانغ برابانغ", "Luang Prabang", "لاوس", "Laos"],
  ["RGN", "يانغون", "Yangon", "ميانمار", "Myanmar"],
  ["MDL", "ماندالاي", "Mandalay", "ميانمار", "Myanmar"],
  ["BWN", "بروناي", "Bandar Seri Begawan", "بروناي", "Brunei"],
  ["DIL", "ديلي", "Dili", "تيمور الشرقية", "Timor-Leste"],

  // ===== شرق آسيا =====
  ["PEK", "بكين", "Beijing", "الصين", "China"],
  ["PVG", "شنغهاي", "Shanghai", "الصين", "China"],
  ["CAN", "قوانغتشو", "Guangzhou", "الصين", "China"],
  ["CTU", "تشنغدو", "Chengdu", "الصين", "China"],
  ["SZX", "شنتشن", "Shenzhen", "الصين", "China"],
  ["KMG", "كونمينغ", "Kunming", "الصين", "China"],
  ["XMN", "شيامن", "Xiamen", "الصين", "China"],
  ["HGH", "هانغتشو", "Hangzhou", "الصين", "China"],
  ["XIY", "شيان", "Xian", "الصين", "China"],
  ["CKG", "تشونغتشينغ", "Chongqing", "الصين", "China"],
  ["NKG", "نانجينغ", "Nanjing", "الصين", "China"],
  ["WUH", "ووهان", "Wuhan", "الصين", "China"],
  ["TAO", "تشينغداو", "Qingdao", "الصين", "China"],
  ["TSN", "تيانجين", "Tianjin", "الصين", "China"],
  ["SYX", "سانيا", "Sanya", "الصين", "China"],
  ["HAK", "هايكو", "Haikou", "الصين", "China"],
  ["CSX", "تشانغشا", "Changsha", "الصين", "China"],
  ["CGO", "تشنغتشو", "Zhengzhou", "الصين", "China"],
  ["SHE", "شنيانغ", "Shenyang", "الصين", "China"],
  ["DLC", "داليان", "Dalian", "الصين", "China"],
  ["URC", "أورومتشي", "Urumqi", "الصين", "China"],
  ["HKG", "هونغ كونغ", "Hong Kong", "هونغ كونغ", "Hong Kong"],
  ["MFM", "ماكاو", "Macau", "ماكاو", "Macau"],
  ["TPE", "تايبيه", "Taipei", "تايوان", "Taiwan"],
  ["KHH", "كاوشيونغ", "Kaohsiung", "تايوان", "Taiwan"],
  ["ICN", "سيول", "Seoul", "كوريا الجنوبية", "South Korea"],
  ["PUS", "بوسان", "Busan", "كوريا الجنوبية", "South Korea"],
  ["CJU", "جيجو", "Jeju", "كوريا الجنوبية", "South Korea"],
  ["NRT", "طوكيو", "Tokyo", "اليابان", "Japan"],
  ["KIX", "أوساكا", "Osaka", "اليابان", "Japan"],
  ["FUK", "فوكوكا", "Fukuoka", "اليابان", "Japan"],
  ["CTS", "سابورو", "Sapporo", "اليابان", "Japan"],
  ["NGO", "ناغويا", "Nagoya", "اليابان", "Japan"],
  ["OKA", "أوكيناوا", "Okinawa", "اليابان", "Japan"],
  ["ULN", "أولان باتور", "Ulaanbaatar", "منغوليا", "Mongolia"],

  // ===== شمال أفريقيا =====
  ["KRT", "الخرطوم", "Khartoum", "السودان", "Sudan"],
  ["PZU", "بورتسودان", "Port Sudan", "السودان", "Sudan"],
  ["JUB", "جوبا", "Juba", "جنوب السودان", "South Sudan"],
  ["TIP", "طرابلس", "Tripoli", "ليبيا", "Libya"],
  ["BEN", "بنغازي", "Benghazi", "ليبيا", "Libya"],
  ["TUN", "تونس", "Tunis", "تونس", "Tunisia"],
  ["MIR", "المنستير", "Monastir", "تونس", "Tunisia"],
  ["DJE", "جربة", "Djerba", "تونس", "Tunisia"],
  ["SFA", "صفاقس", "Sfax", "تونس", "Tunisia"],
  ["ALG", "الجزائر", "Algiers", "الجزائر", "Algeria"],
  ["ORN", "وهران", "Oran", "الجزائر", "Algeria"],
  ["CZL", "قسنطينة", "Constantine", "الجزائر", "Algeria"],
  ["AAE", "عنابة", "Annaba", "الجزائر", "Algeria"],
  ["CMN", "الدار البيضاء", "Casablanca", "المغرب", "Morocco"],
  ["RAK", "مراكش", "Marrakech", "المغرب", "Morocco"],
  ["AGA", "أكادير", "Agadir", "المغرب", "Morocco"],
  ["RBA", "الرباط", "Rabat", "المغرب", "Morocco"],
  ["FEZ", "فاس", "Fes", "المغرب", "Morocco"],
  ["TNG", "طنجة", "Tangier", "المغرب", "Morocco"],
  ["NDR", "الناظور", "Nador", "المغرب", "Morocco"],
  ["NKC", "نواكشوط", "Nouakchott", "موريتانيا", "Mauritania"],

  // ===== غرب أفريقيا =====
  ["DKR", "داكار", "Dakar", "السنغال", "Senegal"],
  ["BJL", "بانجول", "Banjul", "غامبيا", "Gambia"],
  ["BKO", "باماكو", "Bamako", "مالي", "Mali"],
  ["OUA", "واغادوغو", "Ouagadougou", "بوركينا فاسو", "Burkina Faso"],
  ["NIM", "نيامي", "Niamey", "النيجر", "Niger"],
  ["LOS", "لاغوس", "Lagos", "نيجيريا", "Nigeria"],
  ["ABV", "أبوجا", "Abuja", "نيجيريا", "Nigeria"],
  ["KAN", "كانو", "Kano", "نيجيريا", "Nigeria"],
  ["PHC", "بورت هاركورت", "Port Harcourt", "نيجيريا", "Nigeria"],
  ["ACC", "أكرا", "Accra", "غانا", "Ghana"],
  ["KMS", "كوماسي", "Kumasi", "غانا", "Ghana"],
  ["ABJ", "أبيدجان", "Abidjan", "ساحل العاج", "Ivory Coast"],
  ["CKY", "كوناكري", "Conakry", "غينيا", "Guinea"],
  ["FNA", "فريتاون", "Freetown", "سيراليون", "Sierra Leone"],
  ["ROB", "مونروفيا", "Monrovia", "ليبيريا", "Liberia"],
  ["LFW", "لومي", "Lome", "توغو", "Togo"],
  ["COO", "كوتونو", "Cotonou", "بنين", "Benin"],
  ["DLA", "دوالا", "Douala", "الكاميرون", "Cameroon"],
  ["NSI", "ياوندي", "Yaounde", "الكاميرون", "Cameroon"],
  ["RAI", "برايا", "Praia", "الرأس الأخضر", "Cape Verde"],

  // ===== وسط أفريقيا =====
  ["BZV", "برازافيل", "Brazzaville", "الكونغو", "Congo"],
  ["FIH", "كينشاسا", "Kinshasa", "الكونغو الديمقراطية", "DR Congo"],
  ["FBM", "لوبومباشي", "Lubumbashi", "الكونغو الديمقراطية", "DR Congo"],
  ["GOM", "غوما", "Goma", "الكونغو الديمقراطية", "DR Congo"],
  ["LBV", "ليبرفيل", "Libreville", "الغابون", "Gabon"],
  ["SSG", "مالابو", "Malabo", "غينيا الاستوائية", "Equatorial Guinea"],
  ["NDJ", "إنجامينا", "NDjamena", "تشاد", "Chad"],
  ["BGF", "بانغي", "Bangui", "أفريقيا الوسطى", "Central African Republic"],
  ["BJM", "بوجومبورا", "Bujumbura", "بوروندي", "Burundi"],
  ["KGL", "كيغالي", "Kigali", "رواندا", "Rwanda"],

  // ===== شرق أفريقيا =====
  ["ADD", "أديس أبابا", "Addis Ababa", "إثيوبيا", "Ethiopia"],
  ["DIR", "دير داوا", "Dire Dawa", "إثيوبيا", "Ethiopia"],
  ["ASM", "أسمرة", "Asmara", "إريتريا", "Eritrea"],
  ["JIB", "جيبوتي", "Djibouti", "جيبوتي", "Djibouti"],
  ["MGQ", "مقديشو", "Mogadishu", "الصومال", "Somalia"],
  ["HGA", "هرجيسا", "Hargeisa", "الصومال", "Somalia"],
  ["NBO", "نيروبي", "Nairobi", "كينيا", "Kenya"],
  ["MBA", "مومباسا", "Mombasa", "كينيا", "Kenya"],
  ["KIS", "كيسومو", "Kisumu", "كينيا", "Kenya"],
  ["EBB", "إنتيبي", "Entebbe", "أوغندا", "Uganda"],
  ["DAR", "دار السلام", "Dar es Salaam", "تنزانيا", "Tanzania"],
  ["ZNZ", "زنجبار", "Zanzibar", "تنزانيا", "Tanzania"],
  ["JRO", "كليمنجارو", "Kilimanjaro", "تنزانيا", "Tanzania"],
  ["MPM", "مابوتو", "Maputo", "موزمبيق", "Mozambique"],
  ["TNR", "أنتاناناريفو", "Antananarivo", "مدغشقر", "Madagascar"],
  ["MRU", "موريشيوس", "Mauritius", "موريشيوس", "Mauritius"],
  ["SEZ", "فيكتوريا", "Mahe", "سيشل", "Seychelles"],
  ["HAH", "موروني", "Moroni", "جزر القمر", "Comoros"],
  ["LLW", "ليلونغوي", "Lilongwe", "مالاوي", "Malawi"],
  ["LUN", "لوساكا", "Lusaka", "زامبيا", "Zambia"],
  ["HRE", "هراري", "Harare", "زيمبابوي", "Zimbabwe"],
  ["VFA", "شلالات فيكتوريا", "Victoria Falls", "زيمبابوي", "Zimbabwe"],

  // ===== جنوب أفريقيا =====
  ["JNB", "جوهانسبرغ", "Johannesburg", "جنوب أفريقيا", "South Africa"],
  ["CPT", "كيب تاون", "Cape Town", "جنوب أفريقيا", "South Africa"],
  ["DUR", "ديربان", "Durban", "جنوب أفريقيا", "South Africa"],
  ["PLZ", "بورت إليزابيث", "Port Elizabeth", "جنوب أفريقيا", "South Africa"],
  ["WDH", "ويندهوك", "Windhoek", "ناميبيا", "Namibia"],
  ["WVB", "والفيش باي", "Walvis Bay", "ناميبيا", "Namibia"],
  ["GBE", "غابورون", "Gaborone", "بوتسوانا", "Botswana"],
  ["MUB", "ماون", "Maun", "بوتسوانا", "Botswana"],
  ["MSU", "ماسيرو", "Maseru", "ليسوتو", "Lesotho"],
  ["SHO", "مانزيني", "Manzini", "إسواتيني", "Eswatini"],
  ["LAD", "لواندا", "Luanda", "أنغولا", "Angola"],

  // ===== أوروبا =====
  ["LHR", "لندن", "London", "المملكة المتحدة", "United Kingdom"],
  ["LGW", "لندن (غاتويك)", "London Gatwick", "المملكة المتحدة", "United Kingdom"],
  ["MAN", "مانشستر", "Manchester", "المملكة المتحدة", "United Kingdom"],
  ["CDG", "باريس", "Paris", "فرنسا", "France"],
  ["ORY", "باريس (أورلي)", "Paris Orly", "فرنسا", "France"],
  ["FRA", "فرانكفورت", "Frankfurt", "ألمانيا", "Germany"],
  ["MUC", "ميونخ", "Munich", "ألمانيا", "Germany"],
  ["AMS", "أمستردام", "Amsterdam", "هولندا", "Netherlands"],
  ["FCO", "روما", "Rome", "إيطاليا", "Italy"],
  ["MXP", "ميلان", "Milan", "إيطاليا", "Italy"],
  ["MAD", "مدريد", "Madrid", "إسبانيا", "Spain"],
  ["BCN", "برشلونة", "Barcelona", "إسبانيا", "Spain"],
  ["ZRH", "زيورخ", "Zurich", "سويسرا", "Switzerland"],
  ["GVA", "جنيف", "Geneva", "سويسرا", "Switzerland"],
  ["VIE", "فيينا", "Vienna", "النمسا", "Austria"],
  ["PRG", "براغ", "Prague", "التشيك", "Czech Republic"],
  ["BUD", "بودابست", "Budapest", "المجر", "Hungary"],
  ["WAW", "وارسو", "Warsaw", "بولندا", "Poland"],
  ["SJJ", "سراييفو", "Sarajevo", "البوسنة", "Bosnia"],
  ["ATH", "أثينا", "Athens", "اليونان", "Greece"],
  ["SOF", "صوفيا", "Sofia", "بلغاريا", "Bulgaria"],
  ["CPH", "كوبنهاغن", "Copenhagen", "الدانمرك", "Denmark"],
  ["ARN", "ستوكهولم", "Stockholm", "السويد", "Sweden"],
  ["OSL", "أوسلو", "Oslo", "النرويج", "Norway"],
  ["HEL", "هلسنكي", "Helsinki", "فنلندا", "Finland"],
  ["DUB", "دبلن", "Dublin", "أيرلندا", "Ireland"],
  ["SVO", "موسكو", "Moscow", "روسيا", "Russia"],

  // ===== الأمريكتان =====
  ["JFK", "نيويورك", "New York", "الولايات المتحدة", "USA"],
  ["LAX", "لوس أنجلوس", "Los Angeles", "الولايات المتحدة", "USA"],
  ["ORD", "شيكاغو", "Chicago", "الولايات المتحدة", "USA"],
  ["MIA", "ميامي", "Miami", "الولايات المتحدة", "USA"],
  ["SFO", "سان فرانسيسكو", "San Francisco", "الولايات المتحدة", "USA"],
  ["IAH", "هيوستن", "Houston", "الولايات المتحدة", "USA"],
  ["YYZ", "تورونتو", "Toronto", "كندا", "Canada"],
  ["YVR", "فانكوفر", "Vancouver", "كندا", "Canada"],
  ["MEX", "مكسيكو سيتي", "Mexico City", "المكسيك", "Mexico"],
  ["CUN", "كانكون", "Cancun", "المكسيك", "Mexico"],
  ["GRU", "ساو باولو", "Sao Paulo", "البرازيل", "Brazil"],
  ["EZE", "بوينس آيرس", "Buenos Aires", "الأرجنتين", "Argentina"],
  ["BOG", "بوغوتا", "Bogota", "كولومبيا", "Colombia"],
  ["LIM", "ليما", "Lima", "بيرو", "Peru"],

  // ===== أوقيانوسيا =====
  ["SYD", "سيدني", "Sydney", "أستراليا", "Australia"],
  ["MEL", "ميلبورن", "Melbourne", "أستراليا", "Australia"],
  ["AKL", "أوكلاند", "Auckland", "نيوزيلندا", "New Zealand"],
];

export const AIRPORTS = RAW.map(([iata, cityAr, cityEn, countryAr, countryEn]) => ({
  iata,
  cityAr,
  cityEn,
  countryAr,
  countryEn,
}));

export function airportLabel(a, lang = "ar") {
  if (!a) return "";
  return lang === "ar"
    ? `${a.cityAr} (${a.iata}) — ${a.countryAr}`
    : `${a.cityEn} (${a.iata}) — ${a.countryEn}`;
}

export function findAirport(iata) {
  return AIRPORTS.find((a) => a.iata === iata) || null;
}

export function searchAirports(query, lang = "ar", limit = 12) {
  const q = (query || "").trim().toLowerCase();
  if (!q) return AIRPORTS.slice(0, limit);
  return AIRPORTS.filter((a) => {
    const hay = `${a.iata} ${a.cityAr} ${a.cityEn} ${a.countryAr} ${a.countryEn}`.toLowerCase();
    return hay.includes(q);
  }).slice(0, limit);
}