// سجلّ الجهات الحكومية والربط الذكي — خارطة طريق الأتمتة
// كل جهة: ما الغرض من الربط، المنصة المصدر، بيانات الاعتماد المطلوبة، حالة الربط
export const GOV_INTEGRATIONS = [
  {
    key: "cr_wathq",
    group: "سجلات وتجاري",
    entity: { ar: "السجل التجاري", en: "Commercial Register" },
    authority: { ar: "وزارة التجارة (واثق)", en: "Ministry of Commerce (Wathq)" },
    purpose: { ar: "التحقق من تجديد السجل التجاري وتاريخ انتهائه", en: "Verify CR renewal and expiry" },
    needed: { ar: "مفاتيح API من واثق للأعمال (P_ID + Client Key) + رقم الهوية الوطنية الموحدة للمنشأة", en: "Wathq API keys (P_ID + Client Key) + National Unified Number" },
    status: "pending", // pending = يحتاج اعتماد رسمي
    autoActions: ["تحديث تاريخ انتهاء السجل", "إشعار قبل الانتهاء بـ30/15/7 أيام"],
  },
  {
    key: "municipality",
    group: "بلديات",
    entity: { ar: "أمانة/بلدية", en: "Municipality" },
    authority: { ar: "وزارة البلديات والإسكان (بلدي)", en: "Ministry of Municipalities (Balady)" },
    purpose: { ar: "تجديد الترخيص البلدي والتحقق من حالته", en: "Renew municipality license" },
    needed: { ar: "مفاتيح API من منصة بلد + رقم الترخيص", en: "Balady API keys + license number" },
    status: "pending",
    autoActions: ["تجديد الترخيص", "إشعار قبل الانتهاء"],
  },
  {
    key: "industrial",
    group: "صناعة",
    entity: { ar: "وزارة الصناعة والثروة المعدنية", en: "Ministry of Industry & Mineral Resources" },
    authority: { ar: "وزارة الصناعة والثروة المعدنية", en: "Ministry of Industry & Mineral Resources" },
    purpose: { ar: "تجديد الترخيص الصناعي للمنشأة", en: "Renew industrial license" },
    needed: { ar: "مفاتيح API من بوابة الصناعة + رقم الترخيص", en: "Industry portal API keys + license number" },
    status: "pending",
    autoActions: ["تجديد الترخيص", "إشعار قبل الانتهاء"],
  },
  {
    key: "modon",
    group: "مدن صناعية",
    entity: { ar: "هيئة مدن (MODON)", en: "MODON" },
    authority: { ar: "الهيئة السعودية للمدن الصناعية", en: "Saudi Authority for Industrial Cities" },
    purpose: { ar: "تجديد عقد/ترخيص المدينة الصناعية", en: "Renew MODON lease/license" },
    needed: { ar: "مفاتيح API من بوابة هيئة مدن + رقم العقد", en: "MODON API keys + contract number" },
    status: "pending",
    autoActions: ["تجديد العقد", "إشعار قبل الانتهاء"],
  },
  {
    key: "civil_defense",
    group: "سلامة",
    entity: { ar: "الدفاع المدني", en: "Civil Defense" },
    authority: { ar: "المديرية العامة للدفاع المدني", en: "General Directorate of Civil Defense" },
    purpose: { ar: "تجديد ترخيص السلامة", en: "Renew safety license" },
    needed: { ar: "مفاتيح API من بوابة الدفاع المدني للمنشآت + رقم الترخيص", en: "Civil defense portal API keys + license number" },
    status: "pending",
    autoActions: ["تجديد الترخيص", "إشعار قبل الانتهاء"],
  },
  {
    key: "sfda",
    group: "غذاء ودواء",
    entity: { ar: "الهيئة العامة للغذاء والدواء (SFDA)", en: "Food & Drug Authority (SFDA)" },
    authority: { ar: "الهيئة العامة للغذاء والدواء", en: "Saudi Food & Drug Authority" },
    purpose: { ar: "تجديد الترخيص الغذائي/الدوائي والتحقق من حالته", en: "Renew food/drug license" },
    needed: { ar: "مفاتيح API من بوابة SFDA للأعمال + رقم الترخيص", en: "SFDA business API keys + license number" },
    status: "pending",
    autoActions: ["تجديد الترخيص", "إشعار قبل الانتهاء"],
  },
  {
    key: "medical",
    group: "صحة",
    entity: { ar: "الرخصة الصحية / العيادات", en: "Medical License / Clinics" },
    authority: { ar: "وزارة الصحة (بوابة مُوفِّر)", en: "Ministry of Health" },
    purpose: { ar: "تجديد الترخيص الصحي للمنشآت الصحية", en: "Renew medical license" },
    needed: { ar: "مفاتيح API من بوابة مُوفِّر + رقم الترخيص", en: "Mofawed portal API keys + license number" },
    status: "pending",
    autoActions: ["تجديد الترخيص", "إشعار قبل الانتهاء"],
  },
  {
    key: "gosi",
    group: "تأمينات",
    entity: { ar: "التأمينات الاجتماعية (GOSI)", en: "GOSI" },
    authority: { ar: "المؤسسة العامة للتأمينات الاجتماعية", en: "General Organization for Social Insurance" },
    purpose: { ar: "إرسال بيانات الاشتراك الشهري وجلب كشف الاشتراك", en: "Submit monthly GOSI contribution" },
    needed: { ar: "مفاتيح API من بوابة التأمينات + رقم المنشأة في GOSI", en: "GOSI portal API keys + establishment number" },
    status: "pending",
    autoActions: ["إرسال بيانات الموظفين الشهرية", "جلب كشف الاشتراك", "حساب حصة الموظف/صاحب العمل"],
  },
  {
    key: "tourism",
    group: "سياحة",
    entity: { ar: "الهيئة السعودية للسياحة", en: "Saudi Tourism Authority" },
    authority: { ar: "وزارة السياحة", en: "Ministry of Tourism" },
    purpose: { ar: "تجديد الترخيص السياحي (فنادق/معارض/أنشطة سياحية)", en: "Renew tourism license" },
    needed: { ar: "مفاتيح API من بوابة السياحة + رقم الترخيص", en: "Tourism portal API keys + license number" },
    status: "pending",
    autoActions: ["تجديد الترخيص", "إشعار قبل الانتهاء"],
  },
  {
    key: "transport",
    group: "نقل",
    entity: { ar: "هيئة النقل", en: "Transport General Authority" },
    authority: { ar: "الهيئة العامة للنقل", en: "Transport General Authority" },
    purpose: { ar: "تجديد ترخيص نقل (منشآت نقل/سفريات)", en: "Renew transport license" },
    needed: { ar: "مفاتيح API من بوابة هيئة النقل + رقم الترخيص", en: "TGA API keys + license number" },
    status: "pending",
    autoActions: ["تجديد الترخيص", "إشعار قبل الانتهاء"],
  },
  {
    key: "zatca",
    group: "ضريبة",
    entity: { ar: "الزكاة والضريبة والجمارك (ZATCA)", en: "ZATCA" },
    authority: { ar: "هيئة الزكاة والضريبة والجمارك", en: "Zakat, Tax & Customs Authority" },
    purpose: { ar: "ربط الفوترة الإلكترونية (فاتورة) وإرسال الفواتير الآمنة", en: "E-invoice (Fatoora) integration" },
    needed: { ar: "Client ID و Client Secret من ZATCA API + رقم VAT", en: "ZATCA API Client ID/Secret + VAT number" },
    status: "pending",
    autoActions: ["إصدار/إرسال فواتير ضريبية", "مزامنة API مع ZATCA"],
  },
  {
    key: "iqama",
    group: "إقامات",
    entity: { ar: "الإقامات (أبشر أعمال / مقيم)", en: "Iqama (Absher/Muqeem)" },
    authority: { ar: "مقيم (مكتب العمل) + أبشر أعمال (SDAIA)", en: "Muqeem + Absher Business" },
    purpose: { ar: "تحديث تاريخ انتهاء إقامة كل مقيم تلقائياً بعد التجديد أو إصدارها", en: "Auto-update resident Iqama expiry" },
    needed: { ar: "اعتماد موفّر خدمة مع أبشر أعمال + مفاتيح API + رقم المنشأة الموحدة", en: "Absher Business provider accreditation + API keys + establishment number" },
    status: "pending",
    autoActions: ["جلب آخر تاريخ إقامة لكل مقيم", "تحديث حقل iqama_expiry", "إشعار قبل انتهاء الإقامة بـ60/30/7 أيام"],
  },
  {
    key: "traffic",
    group: "مرور ومركبات",
    entity: { ar: "المرور للمركبات", en: "Traffic (Vehicles)" },
    authority: { ar: "الإدارة العامة للمرور (وزارة الداخلية) / أبشر", en: "Traffic General Directorate / Absher" },
    purpose: { ar: "تحديث تجديد استمارات مركبات المنشأة ومعرفة حالتها الزمنية", en: "Auto-update vehicle registration renewal" },
    needed: { ar: "مفاتيح API من بوابة المرور / أبشر + لوحة مركبة + رقم منشأة", en: "Traffic portal API keys + plate number + establishment number" },
    status: "pending",
    autoActions: ["جلب حالة استمارة المركبة", "تحديث تاريخ انتهاء الاستمارة", "إشعار قبل انتهاء الاستمارة"],
  },
  {
    key: "mudad_wps",
    group: "رواتب",
    entity: { ar: "مدد (حماية الأجور WPS)", en: "Mudad (WPS)" },
    authority: { ar: "وزارة الموارد البشرية (منصة مدد)", en: "Ministry of HR (Mudad)" },
    purpose: { ar: "إرسال كشف الرواتب المعتمد تلقائياً لحماية الأجور WPS", en: "Submit approved payroll to WPS" },
    needed: { ar: "اعتماد موفّر خدمة رواتب مع مدد + Client ID/Secret + الرقم الموحد للمنشأة", en: "Mudad payroll provider accreditation + Client ID/Secret + establishment unified number" },
    status: "pending",
    autoActions: ["توليد ملف WPS بصيغة مدّد المعيارية", "إرسال الكشف عند الاعتماد", "جلب حالة القبول/الرفض"],
  },
  {
    key: "qiwa_ajeer",
    group: "موارد بشرية",
    entity: { ar: "قوى / عاجل (MHRSD)", en: "Qiwa / Ajeer (MHRSD)" },
    authority: { ar: "وزارة الموارد البشرية والتنمية الاجتماعية", en: "Ministry of HR & Social Development" },
    purpose: { ar: "نقل وتعديل بيانات الموظفين وخدمات العمالة وإصدار رخص العمل", en: "Employee transfers and work permits" },
    needed: { ar: "مفاتيح API من قوى/عاجل + رقم المنشأة الموحدة", en: "Qiwa/Ajeer API keys + establishment number" },
    status: "pending",
    autoActions: ["نقل/تعديل بيانات موظف", "إصدار رخصة عمل", "جلب وضع العامل"],
  },
];

export const STATUS_META = {
  pending: { ar: "يحتاج اعتماد رسمي", en: "Needs official accreditation", cls: "bg-amber-50 text-amber-700 border-amber-200", dot: "bg-amber-500" },
  ready: { ar: "جاهز للتفعيل", en: "Ready to activate", cls: "bg-emerald-50 text-emerald-700 border-emerald-200", dot: "bg-emerald-500" },
  live: { ar: "مفعّل", en: "Live", cls: "bg-violet-50 text-violet-700 border-violet-200", dot: "bg-violet-500" },
  na: { ar: "لا ينطبق", en: "Not applicable", cls: "bg-slate-100 text-slate-500 border-slate-200", dot: "bg-slate-400" },
};