// مرجع سياسة العمل والإنذارات — مبني على لائحة تنظيم العمل المعتمدة من وزارة الموارد البشرية
// مقسّمة إلى ثلاثة أبواب وفق جداول المخالفات والجزاءات الرسمية

// ترتيب درجات الجزاء (للاقتراح الآلي)
const PENALTY_ORDER = ["warning", "10pct", "25pct", "50pct", "75pct", "1day", "2days", "3days", "4days", "5days", "deprive_promotion", "dismiss_with", "dismiss_without"];

// ===== الأبواب =====
export const VIOLATION_CHAPTERS = [
  { id: "attendance", ar: "أولاً: مخالفات تتعلق بمواعيد العمل", en: "Chapter I: Working Hours Violations" },
  { id: "work_order", ar: "ثانياً: مخالفات تتعلق بتنظيم العمل", en: "Chapter II: Work Organization Violations" },
  { id: "conduct", ar: "ثالثاً: مخالفات تتعلق بسلوك العامل", en: "Chapter III: Employee Conduct Violations" },
];

// ===== قائمة المخالفات الكاملة =====
export const VIOLATION_CATEGORIES = [

  // ──────────────────────────────────────────
  // الباب الأول: مخالفات مواعيد العمل (م 1–16)
  // ──────────────────────────────────────────
  {
    id: "late_15_no_impact",
    chapter: "attendance",
    ar: "التأخر حتى 15 دقيقة — دون تعطيل الغير",
    en: "Late up to 15 min — no disruption to others",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 1.",
    articleEn: "Internal work regulations — violations table, item 1.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 5% | ثالث: 10% | رابع: 20%",
    consequenceEn: "1st: written warning | 2nd: 5% | 3rd: 10% | 4th: 20%",
    severity: "low",
  },
  {
    id: "late_15_with_impact",
    chapter: "attendance",
    ar: "التأخر حتى 15 دقيقة — مع تعطيل عمال آخرين",
    en: "Late up to 15 min — with disruption to others",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 2.",
    articleEn: "Internal work regulations — violations table, item 2.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 15% | ثالث: 25% | رابع: 50%",
    consequenceEn: "1st: written warning | 2nd: 15% | 3rd: 25% | 4th: 50%",
    severity: "medium",
  },
  {
    id: "late_15_30_no_impact",
    chapter: "attendance",
    ar: "التأخر 15–30 دقيقة — دون تعطيل الغير",
    en: "Late 15–30 min — no disruption",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 3.",
    articleEn: "Internal work regulations — violations table, item 3.",
    consequenceAr: "أول مرة: 10% | ثاني: 15% | ثالث: 25% | رابع: 50%",
    consequenceEn: "1st: 10% | 2nd: 15% | 3rd: 25% | 4th: 50%",
    severity: "medium",
  },
  {
    id: "late_15_30_with_impact",
    chapter: "attendance",
    ar: "التأخر 15–30 دقيقة — مع تعطيل عمال آخرين",
    en: "Late 15–30 min — with disruption",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 4.",
    articleEn: "Internal work regulations — violations table, item 4.",
    consequenceAr: "أول مرة: 25% | ثاني: 50% | ثالث: 75% | رابع: يوم كامل",
    consequenceEn: "1st: 25% | 2nd: 50% | 3rd: 75% | 4th: 1 day",
    severity: "medium",
  },
  {
    id: "late_30_60_no_impact",
    chapter: "attendance",
    ar: "التأخر 30–60 دقيقة — دون تعطيل الغير",
    en: "Late 30–60 min — no disruption",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 5.",
    articleEn: "Internal work regulations — violations table, item 5.",
    consequenceAr: "أول مرة: 25% | ثاني: 50% | ثالث: 75% | رابع: يوم كامل",
    consequenceEn: "1st: 25% | 2nd: 50% | 3rd: 75% | 4th: 1 day",
    severity: "medium",
  },
  {
    id: "late_30_60_with_impact",
    chapter: "attendance",
    ar: "التأخر 30–60 دقيقة — مع تعطيل عمال آخرين",
    en: "Late 30–60 min — with disruption",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 6. بالإضافة إلى حسم أجر دقائق التأخر.",
    articleEn: "Internal work regulations — violations table, item 6. Plus deduction of late minutes.",
    consequenceAr: "أول مرة: 30% | ثاني: 50% | ثالث: يوم | رابع: يومان + حسم دقائق التأخر",
    consequenceEn: "1st: 30% | 2nd: 50% | 3rd: 1 day | 4th: 2 days + late minutes deduction",
    severity: "medium",
  },
  {
    id: "late_over_hour",
    chapter: "attendance",
    ar: "التأخر أكثر من ساعة دون إذن",
    en: "Late more than 1 hour without permission",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 7. بالإضافة إلى حسم أجر ساعات التأخر.",
    articleEn: "Internal work regulations — violations table, item 7. Plus deduction of late hours.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: يوم | ثالث: يومان | رابع: 3 أيام + حسم ساعات التأخر",
    consequenceEn: "1st: written warning | 2nd: 1 day | 3rd: 2 days | 4th: 3 days + hours deduction",
    severity: "high",
  },
  {
    id: "early_leave_15",
    chapter: "attendance",
    ar: "الانصراف المبكر حتى 15 دقيقة دون إذن",
    en: "Early departure up to 15 min without permission",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 8. بالإضافة إلى حسم أجر مدة ترك العمل.",
    articleEn: "Internal work regulations — violations table, item 8. Plus time deduction.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 25% | رابع: يوم",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 25% | 4th: 1 day",
    severity: "low",
  },
  {
    id: "early_leave_over_15",
    chapter: "attendance",
    ar: "الانصراف المبكر أكثر من 15 دقيقة دون إذن",
    en: "Early departure over 15 min without permission",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 9. بالإضافة إلى حسم أجر مدة ترك العمل.",
    articleEn: "Internal work regulations — violations table, item 9. Plus time deduction.",
    consequenceAr: "أول مرة: 10% | ثاني: 25% | ثالث: 50% | رابع: يوم",
    consequenceEn: "1st: 10% | 2nd: 25% | 3rd: 50% | 4th: 1 day",
    severity: "medium",
  },
  {
    id: "stay_after_hours",
    chapter: "attendance",
    ar: "البقاء في مكان العمل بعد انتهاء الدوام بدون إذن",
    en: "Staying at workplace after hours without permission",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 10.",
    articleEn: "Internal work regulations — violations table, item 10.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 25% | رابع: يوم",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 25% | 4th: 1 day",
    severity: "low",
  },
  {
    id: "absence_1day",
    chapter: "attendance",
    ar: "الغياب يوماً واحداً بدون إذن أو عذر",
    en: "Absent 1 day without permission or excuse",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 11.",
    articleEn: "Internal work regulations — violations table, item 11.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 4 أيام | رابع: الحرمان من الترقية/العلاوة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 4 days | 4th: deprivation of promotion/increment",
    severity: "medium",
  },
  {
    id: "absence_2_6days",
    chapter: "attendance",
    ar: "الغياب المتصل 2–6 أيام بدون إذن أو عذر",
    en: "Consecutive absence 2–6 days without excuse",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 12. بالإضافة إلى حسم أجر مدة الغياب.",
    articleEn: "Internal work regulations — violations table, item 12. Plus absence days deduction.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 4 أيام | رابع: الحرمان من الترقية/العلاوة + حسم الغياب",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 4 days | 4th: deprivation + absence deduction",
    severity: "high",
  },
  {
    id: "absence_7_10days",
    chapter: "attendance",
    ar: "الغياب المتصل 7–10 أيام بدون إذن أو عذر",
    en: "Consecutive absence 7–10 days without excuse",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 13. بالإضافة إلى حسم أجر مدة الغياب.",
    articleEn: "Internal work regulations — violations table, item 13. Plus absence deduction.",
    consequenceAr: "أول مرة: 4 أيام | ثاني: 5 أيام | ثالث: الحرمان من الترقية | رابع: فصل مع المكافأة (إذا لم يتجاوز إجمالي الغياب 30 يوماً)",
    consequenceEn: "1st: 4 days | 2nd: 5 days | 3rd: deprivation | 4th: dismissal with gratuity (if total ≤30 days)",
    severity: "high",
  },
  {
    id: "absence_11_14days",
    chapter: "attendance",
    ar: "الغياب المتصل 11–14 يوماً بدون إذن أو عذر",
    en: "Consecutive absence 11–14 days without excuse",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات، البند 14 / المادة 80.",
    articleEn: "Internal work regulations — violations table, item 14 / Article 80.",
    consequenceAr: "أول مرة: 5 أيام | ثاني: الحرمان من الترقية + إنذار بالفصل | ثالث: فصل وفق المادة 80",
    consequenceEn: "1st: 5 days | 2nd: deprivation + warning of termination | 3rd: termination per Article 80",
    severity: "termination",
  },
  {
    id: "absence_over_15_consecutive",
    chapter: "attendance",
    ar: "الانقطاع عن العمل أكثر من 15 يوماً متصلة",
    en: "Absence more than 15 consecutive days",
    articleAr: "المادة 80 من نظام العمل — الفصل دون مكافأة أو تعويض على أن يسبقه إنذار كتابي بعد 10 أيام.",
    articleEn: "Article 80 — dismissal without gratuity preceded by written warning after 10 days.",
    consequenceAr: "فصل دون مكافأة أو تعويض (يسبقه إنذار كتابي بعد 10 أيام غياب)",
    consequenceEn: "Dismissal without gratuity or compensation (written warning after 10 days)",
    severity: "termination",
  },
  {
    id: "absence_over_30_intermittent",
    chapter: "attendance",
    ar: "الغياب المتقطع أكثر من 30 يوماً خلال السنة العقدية",
    en: "Intermittent absence exceeding 30 days in one contract year",
    articleAr: "المادة 80 من نظام العمل — الفصل دون مكافأة أو تعويض على أن يسبقه إنذار كتابي بعد 20 يوماً.",
    articleEn: "Article 80 — dismissal without gratuity preceded by written warning after 20 days.",
    consequenceAr: "فصل دون مكافأة أو تعويض (يسبقه إنذار كتابي بعد 20 يوماً غياباً متقطعاً)",
    consequenceEn: "Dismissal without gratuity (written warning after 20 intermittent days)",
    severity: "termination",
  },

  // ──────────────────────────────────────────
  // الباب الثاني: مخالفات تنظيم العمل (م 1–18)
  // ──────────────────────────────────────────
  {
    id: "wrong_location",
    chapter: "work_order",
    ar: "التواجد دون مبرر في غير مكان العمل المخصص",
    en: "Being in unauthorized area during working hours",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 1.",
    articleEn: "Internal work regulations — work organization table, item 1.",
    consequenceAr: "أول مرة: 10% | ثاني: 25% | ثالث: 50% | رابع: يوم كامل",
    consequenceEn: "1st: 10% | 2nd: 25% | 3rd: 50% | 4th: 1 day",
    severity: "low",
  },
  {
    id: "unauthorized_visitors",
    chapter: "work_order",
    ar: "استقبال زوار لأغراض شخصية في مكان العمل دون إذن",
    en: "Receiving personal visitors at workplace without permission",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 2.",
    articleEn: "Internal work regulations — work organization table, item 2.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 15% | رابع: 25%",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 15% | 4th: 25%",
    severity: "low",
  },
  {
    id: "personal_use_equipment",
    chapter: "work_order",
    ar: "استعمال آلات ومعدات المنشأة لأغراض شخصية دون إذن",
    en: "Using company equipment for personal purposes without permission",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 3.",
    articleEn: "Internal work regulations — work organization table, item 3.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 25% | رابع: 50%",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 25% | 4th: 50%",
    severity: "medium",
  },
  {
    id: "unauthorized_work",
    chapter: "work_order",
    ar: "تدخل العامل في عمل ليس من اختصاصه",
    en: "Employee interfering in work outside their scope",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 4.",
    articleEn: "Internal work regulations — work organization table, item 4.",
    consequenceAr: "أول مرة: 50% | ثاني: يوم | ثالث: يومان | رابع: 3 أيام",
    consequenceEn: "1st: 50% | 2nd: 1 day | 3rd: 2 days | 4th: 3 days",
    severity: "medium",
  },
  {
    id: "wrong_entry_exit",
    chapter: "work_order",
    ar: "الخروج أو الدخول من غير المكان المخصص",
    en: "Using unauthorized entry/exit points",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 5.",
    articleEn: "Internal work regulations — work organization table, item 5.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 15% | رابع: 25%",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 15% | 4th: 25%",
    severity: "low",
  },
  {
    id: "equipment_neglect",
    chapter: "work_order",
    ar: "الإهمال في تنظيف الآلات وصيانتها أو عدم التبليغ عن خللها",
    en: "Neglecting to clean/maintain equipment or report malfunctions",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 6.",
    articleEn: "Internal work regulations — work organization table, item 6.",
    consequenceAr: "أول مرة: 50% | ثاني: يوم | ثالث: يومان | رابع: 3 أيام",
    consequenceEn: "1st: 50% | 2nd: 1 day | 3rd: 2 days | 4th: 3 days",
    severity: "medium",
  },
  {
    id: "tools_not_stored",
    chapter: "work_order",
    ar: "عدم إعادة أدوات الإصلاح والصيانة إلى أماكنها بعد الانتهاء",
    en: "Failure to return tools/maintenance items to designated places",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 7.",
    articleEn: "Internal work regulations — work organization table, item 7.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 25% | ثالث: 50% | رابع: يوم",
    consequenceEn: "1st: written warning | 2nd: 25% | 3rd: 50% | 4th: 1 day",
    severity: "low",
  },
  {
    id: "destroy_notices",
    chapter: "work_order",
    ar: "تمزيق أو إتلاف إعلانات أو بلاغات الإدارة",
    en: "Tearing or damaging company notices or announcements",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 8.",
    articleEn: "Internal work regulations — work organization table, item 8.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "custody_neglect",
    chapter: "work_order",
    ar: "الإهمال في العهد التي بحوزة العامل (سيارات، أجهزة، معدات...)",
    en: "Neglecting company assets in custody (vehicles, devices, equipment...)",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 9.",
    articleEn: "Internal work regulations — work organization table, item 9.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "eating_wrong_place",
    chapter: "work_order",
    ar: "الأكل في مكان العمل أو في غير أوقات الراحة",
    en: "Eating in the workplace or outside break times",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 10.",
    articleEn: "Internal work regulations — work organization table, item 10.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 15% | رابع: 25%",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 15% | 4th: 25%",
    severity: "low",
  },
  {
    id: "sleeping",
    chapter: "work_order",
    ar: "النوم أثناء العمل",
    en: "Sleeping during working hours",
    articleAr: "المادة 41 من نظام العمل — لائحة تنظيم العمل، جدول المخالفات البند 11.",
    articleEn: "Article 41 — internal work regulations, item 11.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 25% | رابع: 50%",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 25% | 4th: 50%",
    severity: "medium",
  },
  {
    id: "sleeping_vigilance",
    chapter: "work_order",
    ar: "النوم في الحالات التي تستدعي يقظة مستمرة",
    en: "Sleeping in situations requiring continuous vigilance",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 12.",
    articleEn: "Internal work regulations — work organization table, item 12.",
    consequenceAr: "أول مرة: 50% | ثاني: يوم | ثالث: يومان | رابع: 3 أيام",
    consequenceEn: "1st: 50% | 2nd: 1 day | 3rd: 2 days | 4th: 3 days",
    severity: "high",
  },
  {
    id: "loitering",
    chapter: "work_order",
    ar: "التسكع أو وجود العامل في غير مكان عمله أثناء الدوام",
    en: "Loitering or being outside work area during working hours",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 13.",
    articleEn: "Internal work regulations — work organization table, item 13.",
    consequenceAr: "أول مرة: 10% | ثاني: 25% | ثالث: 50% | رابع: يوم",
    consequenceEn: "1st: 10% | 2nd: 25% | 3rd: 50% | 4th: 1 day",
    severity: "low",
  },
  {
    id: "attendance_fraud",
    chapter: "work_order",
    ar: "التلاعب في إثبات الحضور والانصراف",
    en: "Manipulating attendance records",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 14.",
    articleEn: "Internal work regulations — work organization table, item 14.",
    consequenceAr: "أول مرة: يوم | ثاني: يومان | ثالث: الحرمان من الترقية/العلاوة | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 1 day | 2nd: 2 days | 3rd: deprivation of promotion | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "disobedience",
    chapter: "work_order",
    ar: "عدم إطاعة الأوامر العادية أو عدم تنفيذ التعليمات المعلقة",
    en: "Failure to follow work orders or posted instructions",
    articleAr: "المادة 41 من نظام العمل — لائحة تنظيم العمل، جدول المخالفات البند 15.",
    articleEn: "Article 41 — internal work regulations, item 15.",
    consequenceAr: "أول مرة: 25% | ثاني: 50% | ثالث: يوم | رابع: يومان",
    consequenceEn: "1st: 25% | 2nd: 50% | 3rd: 1 day | 4th: 2 days",
    severity: "medium",
  },
  {
    id: "incitement",
    chapter: "work_order",
    ar: "التحريض على مخالفة الأوامر والتعليمات الخاصة بالعمل",
    en: "Inciting others to violate work orders or instructions",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 16.",
    articleEn: "Internal work regulations — work organization table, item 16.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "smoking_prohibited",
    chapter: "work_order",
    ar: "التدخين في الأماكن المحظورة المعلن عنها",
    en: "Smoking in designated prohibited areas",
    articleAr: "لائحة تنظيم العمل — جدول المخالفات (تنظيم العمل)، البند 17.",
    articleEn: "Internal work regulations — work organization table, item 17.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "safety_negligence",
    chapter: "work_order",
    ar: "الإهمال أو التهاون في العمل مما قد يضر بصحة العمال أو يتلف المواد",
    en: "Negligence that may harm workers' safety or damage materials/equipment",
    articleAr: "المادة 41 ونظام السلامة — لائحة تنظيم العمل، جدول المخالفات البند 18.",
    articleEn: "Article 41 and safety regulations — violations table, item 18.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },

  // ──────────────────────────────────────────
  // الباب الثالث: مخالفات سلوك العامل (م 1–16)
  // ──────────────────────────────────────────
  {
    id: "fighting",
    chapter: "conduct",
    ar: "التشاجر مع الزملاء أو الغير أو إحداث مشاغبات في العمل",
    en: "Fighting with colleagues or others, or causing disturbances",
    articleAr: "المادة 41 من نظام العمل — لائحة تنظيم العمل، جدول سلوك العامل البند 1.",
    articleEn: "Article 41 — employee conduct table, item 1.",
    consequenceAr: "أول مرة: يوم | ثاني: يومان | ثالث: 3 أيام | رابع: 5 أيام",
    consequenceEn: "1st: 1 day | 2nd: 2 days | 3rd: 3 days | 4th: 5 days",
    severity: "high",
  },
  {
    id: "fake_illness",
    chapter: "conduct",
    ar: "التمارض أو ادعاء الإصابة كذباً",
    en: "Feigning illness or falsely claiming work injury",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 2.",
    articleEn: "Employee conduct table, item 2.",
    consequenceAr: "أول مرة: يوم | ثاني: يومان | ثالث: 3 أيام | رابع: 5 أيام",
    consequenceEn: "1st: 1 day | 2nd: 2 days | 3rd: 3 days | 4th: 5 days",
    severity: "high",
  },
  {
    id: "refuse_medical",
    chapter: "conduct",
    ar: "الامتناع عن الكشف الطبي أو رفض التعليمات الطبية",
    en: "Refusing medical examination or medical instructions during treatment",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 3.",
    articleEn: "Employee conduct table, item 3.",
    consequenceAr: "أول مرة: يوم | ثاني: يومان | ثالث: 3 أيام | رابع: 5 أيام",
    consequenceEn: "1st: 1 day | 2nd: 2 days | 3rd: 3 days | 4th: 5 days",
    severity: "medium",
  },
  {
    id: "health_instructions",
    chapter: "conduct",
    ar: "مخالفة التعليمات الصحية المعلقة بأماكن العمل",
    en: "Violating posted health instructions at the workplace",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 4.",
    articleEn: "Employee conduct table, item 4.",
    consequenceAr: "أول مرة: 50% | ثاني: يوم | ثالث: يومان | رابع: 5 أيام",
    consequenceEn: "1st: 50% | 2nd: 1 day | 3rd: 2 days | 4th: 5 days",
    severity: "medium",
  },
  {
    id: "graffiti",
    chapter: "conduct",
    ar: "الكتابة على جدران المنشأة أو لصق إعلانات غير مصرح بها",
    en: "Writing on company walls or posting unauthorized notices",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 5.",
    articleEn: "Employee conduct table, item 5.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: 10% | ثالث: 25% | رابع: 50%",
    consequenceEn: "1st: written warning | 2nd: 10% | 3rd: 25% | 4th: 50%",
    severity: "low",
  },
  {
    id: "refuse_inspection",
    chapter: "conduct",
    ar: "رفض التفتيش الإداري عند الانصراف",
    en: "Refusing administrative inspection upon leaving",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 6.",
    articleEn: "Employee conduct table, item 6.",
    consequenceAr: "أول مرة: 25% | ثاني: 50% | ثالث: يوم | رابع: يومان",
    consequenceEn: "1st: 25% | 2nd: 50% | 3rd: 1 day | 4th: 2 days",
    severity: "medium",
  },
  {
    id: "cash_delay",
    chapter: "conduct",
    ar: "عدم تسليم النقود المحصلة في المواعيد المحددة",
    en: "Failure to submit collected cash on time without acceptable reason",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 7.",
    articleEn: "Employee conduct table, item 7.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "no_ppe",
    chapter: "conduct",
    ar: "الامتناع عن ارتداء ملابس وأجهزة الوقاية والسلامة",
    en: "Refusing to wear required safety/protective gear",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 8.",
    articleEn: "Employee conduct table, item 8.",
    consequenceAr: "أول مرة: إنذار كتابي | ثاني: يوم | ثالث: يومان | رابع: 5 أيام",
    consequenceEn: "1st: written warning | 2nd: 1 day | 3rd: 2 days | 4th: 5 days",
    severity: "medium",
  },
  {
    id: "khalwa",
    chapter: "conduct",
    ar: "تعمد الخلوة مع الجنس الآخر في أماكن العمل",
    en: "Deliberately being in seclusion with opposite gender at workplace",
    articleAr: "المادة 37 من لائحة تنظيم العمل — جدول سلوك العامل، البند 9.",
    articleEn: "Article 37 — employee conduct table, item 9.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "indecency",
    chapter: "conduct",
    ar: "الإيحاء للآخرين بما يخدش الحياء قولاً أو فعلاً",
    en: "Indecent gestures or behavior towards others (verbal or physical)",
    articleAr: "المادة 37–38 من لائحة تنظيم العمل — جدول سلوك العامل، البند 10.",
    articleEn: "Articles 37–38 — employee conduct table, item 10.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "verbal_assault_colleague",
    chapter: "conduct",
    ar: "الاعتداء القولي أو الإشاري على الزملاء (الشتم أو التحقير)",
    en: "Verbal or signal-based assault on colleagues (insults or humiliation)",
    articleAr: "المادة 80/7 من نظام العمل — جدول سلوك العامل، البند 11.",
    articleEn: "Article 80(7) — employee conduct table, item 11.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "physical_assault_colleague",
    chapter: "conduct",
    ar: "الاعتداء الجسدي على زملاء العمل أو غيرهم",
    en: "Physical assault on colleagues or others",
    articleAr: "المادة 80/7 من نظام العمل — الفسخ دون مكافأة أو إشعار أو تعويض.",
    articleEn: "Article 80(7) — termination without gratuity, notice, or compensation.",
    consequenceAr: "فصل بدون مكافأة أو إشعار أو تعويض (المادة 80)",
    consequenceEn: "Dismissal without gratuity, notice, or compensation (Article 80)",
    severity: "termination",
  },
  {
    id: "assault_manager",
    chapter: "conduct",
    ar: "الاعتداء الجسدي أو القولي على صاحب العمل أو المدير أو الرؤساء",
    en: "Physical or verbal assault on employer, manager, or supervisors",
    articleAr: "المادة 80/7 من نظام العمل — الفسخ دون مكافأة أو إشعار أو تعويض.",
    articleEn: "Article 80(7) — termination without gratuity, notice, or compensation.",
    consequenceAr: "فصل بدون مكافأة أو إشعار أو تعويض (المادة 80)",
    consequenceEn: "Dismissal without gratuity, notice, or compensation (Article 80)",
    severity: "termination",
  },
  {
    id: "false_complaint",
    chapter: "conduct",
    ar: "تقديم بلاغ أو شكوى كيدية",
    en: "Filing a malicious complaint or report",
    articleAr: "لائحة تنظيم العمل — جدول سلوك العامل، البند 14.",
    articleEn: "Employee conduct table, item 14.",
    consequenceAr: "أول مرة: 3 أيام | ثاني: 5 أيام | ثالث: فصل مع المكافأة",
    consequenceEn: "1st: 3 days | 2nd: 5 days | 3rd: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "refuse_investigation",
    chapter: "conduct",
    ar: "عدم الامتثال لطلب لجنة التحقيق بالحضور",
    en: "Failure to appear before the investigation committee when requested",
    articleAr: "المادة 40 من لائحة تنظيم العمل — جدول سلوك العامل، البند 15.",
    articleEn: "Article 40 — employee conduct table, item 15.",
    consequenceAr: "أول مرة: يومان | ثاني: 3 أيام | ثالث: 5 أيام | رابع: فصل مع المكافأة",
    consequenceEn: "1st: 2 days | 2nd: 3 days | 3rd: 5 days | 4th: dismissal with gratuity",
    severity: "high",
  },
  {
    id: "no_uniform",
    chapter: "conduct",
    ar: "عدم الالتزام بالزي الرسمي المعتمد في المنشأة",
    en: "Not wearing the officially approved uniform",
    articleAr: "المادة 37 من لائحة تنظيم العمل — جدول سلوك العامل، البند 16.",
    articleEn: "Article 37 — employee conduct table, item 16.",
    consequenceAr: "أول مرة: يوم | ثاني: يومان | ثالث: 3 أيام | رابع: 5 أيام",
    consequenceEn: "1st: 1 day | 2nd: 2 days | 3rd: 3 days | 4th: 5 days",
    severity: "medium",
  },

  // ──────────────────────────────────────────
  // مخالفات إضافية من نظام العمل (م 80)
  // ──────────────────────────────────────────
  {
    id: "disclosure",
    chapter: "conduct",
    ar: "إفشاء أسرار العمل",
    en: "Disclosing work secrets",
    articleAr: "المادة 41 و80/5 من نظام العمل — واجب المحافظة على أسرار العمل.",
    articleEn: "Article 41 and 80(5) — duty to preserve work secrets.",
    consequenceAr: "إنذار أو فصل حسب جسامة الإخلال (المادة 80)",
    consequenceEn: "Warning or termination per severity of breach (Article 80)",
    severity: "high",
  },
  {
    id: "product_damage",
    chapter: "work_order",
    ar: "إتلاف منتجات أو ممتلكات العمل عمداً أو بإهمال جسيم",
    en: "Intentional or grossly negligent damage to company property",
    articleAr: "المادة 77 و80/6 من نظام العمل — التعويض عن الضرر والفسخ عند العمد أو الإهمال الجسيم.",
    articleEn: "Article 77 and 80(6) — compensation and termination on intent or gross negligence.",
    consequenceAr: "إنذار أو فصل + التعويض عن التلف حسب الجسامة",
    consequenceEn: "Warning or termination + compensation for damage",
    severity: "high",
  },
  {
    id: "other",
    chapter: "conduct",
    ar: "مخالفة أخرى وفق لائحة تنظيم العمل",
    en: "Other violation per internal work regulations",
    articleAr: "لائحة تنظيم العمل الداخلية المعتمدة لدى وزارة الموارد البشرية.",
    articleEn: "Internal work regulations registered with the Ministry of Human Resources.",
    consequenceAr: "حسب قواعد اللائحة",
    consequenceEn: "Per internal regulations",
    severity: "low",
  },
];

export const WARNING_LEVELS = [
  { id: "first",       ar: "إنذار أول",           en: "First warning",         cls: "bg-amber-50 text-amber-700 border-amber-200",    sev: "low" },
  { id: "second",      ar: "إنذار ثانٍ",           en: "Second warning",        cls: "bg-orange-50 text-orange-700 border-orange-200",  sev: "medium" },
  { id: "third",       ar: "إنذار ثالث (نهائي)",   en: "Third (final) warning", cls: "bg-rose-50 text-rose-700 border-rose-200",        sev: "high" },
  { id: "termination", ar: "فسخ العقد (فصل)",      en: "Contract termination",  cls: "bg-red-600 text-white border-red-700",            sev: "termination" },
];

const ORDER = ["first", "second", "third", "termination"];

export function suggestLevel(existingCount, category) {
  if (!category) return "first";
  if (category.severity === "termination") return "termination";
  return ORDER[Math.min(existingCount, ORDER.length - 1)];
}

export function categoryById(id, lang) {
  const c = VIOLATION_CATEGORIES.find((x) => x.id === id);
  if (!c) return null;
  return {
    ...c,
    label: lang === "ar" ? c.ar : c.en,
    article: lang === "ar" ? c.articleAr : c.articleEn,
    consequence: lang === "ar" ? c.consequenceAr : c.consequenceEn,
  };
}

export function levelById(id, lang) {
  const l = WARNING_LEVELS.find((x) => x.id === id) || WARNING_LEVELS[0];
  return { ...l, label: lang === "ar" ? l.ar : l.en };
}

export function categoriesByChapter(chapterId) {
  return VIOLATION_CATEGORIES.filter((c) => c.chapter === chapterId);
}

export const LABOR_POLICY_INTRO = {
  ar: "تستند سياسة العمل والإنذارات إلى لائحة تنظيم العمل المعتمدة من وزارة الموارد البشرية والتنمية الاجتماعية، المبنية على نظام العمل السعودي الصادر بالمرسوم الملكي (م/51). يُصدر الإنذار بعد إجراء جلسة وتحقق من ثبوت المخالفة على الموظف، ويُرسل مباشرة إلى بوابة الموظف الذاتية — إذ يُعتبر الإنذار نافذاً ومعتمداً بمجرد إرساله، ولا يُحتجب به على الموظف إلا بعد تحقيق وإثبات.",
  en: "The labor policy and warnings are based on the internal work regulations approved by the Ministry of Human Resources and Social Development, built on the Saudi Labor Law (Royal Decree M/51). A warning is issued after a session is held and the violation is established; it is sent directly to the employee self-service portal — the warning is effective upon sending, and cannot be held against the worker without investigation and proof.",
};