// مرجع سياسة العمل والإنذارات — مبني على نظام العمل السعودي — متعدد اللغات
const cap = (l) => ({ ar: "Ar", en: "En", hi: "Hi", ne: "Ne", bn: "Bn", fil: "Fil", ur: "Ur" })[l] || "En";

export const VIOLATION_CATEGORIES = [
  {
    id: "absence_short",
    ar: "الغياب بدون عذر (يوم إلى يومين)", en: "Unexcused absence (1–2 days)",
    hi: "बिना बहाने अनुपस्थिति (1–2 दिन)", ne: "बिना बहानाको अनुपस्थिति (१–२ दिन)", bn: "কারণ ছাড়া অনুপস্থিতি (১–২ দিন)", fil: "Hindi pinapayagang kawalan (1–2 araw)", ur: "بغیر وجہ غیر حاضری (1 سے 2 دن)",
    articleAr: "المادة 76 — لصاحب العمل خصم أجر أيام الغياب، ولا يجوز الخصم أكثر من أجر خمسة أيام في الشهر.",
    articleEn: "Article 76 — the employer may deduct wages for the days of absence, not exceeding five days' wages per month.",
    articleHi: "अनुच्छेद 76 — नियोक्ता अनुपस्थिति के दिनों का वेतन काट सकता है, मास में पाँच दिन के वेतन से अधिक नहीं।",
    articleNe: "धारा ७६ — नियोक्ताले अनुपस्थिति दिनको ज्याला कट्टा गर्न सक्छ, महिनामा पाँच दिनको ज्याला भन्दा बढी हुँदैन।",
    articleBn: "ধারা ৭৬ — নিয়োগকর্তা অনুপস্থিতির দিনের মজুরি কাটতে পারে, মাসে পাঁচ দিনের মজুরির বেশি নয়।",
    articleFil: "Artikulo 76 — maaaring bawasan ng employer ang sahod sa mga araw ng kawalan, hindi hihigit sa limang araw bawat buwan.",
    articleUr: "مادہ 76 — ملازمت دہندہ غیر حاضری کے دنوں کی تنخواہ کاٹ سکتا ہے، ماہ میں پانچ دن کی تنخواہ سے زیادہ نہیں۔",
    consequenceAr: "إنذار أول + خصم أيام الغياب.",
    consequenceEn: "First warning + deduction of absence days.",
    consequenceHi: "पहली चेतावनी + अनुपस्थिति दिनों का कटौती।",
    consequenceNe: "पहिलो चेतावनी + अनुपस्थिति दिनको कटौती।",
    consequenceBn: "প্রথম সতর্কতা + অনুপস্থিতি দিন কর্তন।",
    consequenceFil: "Unang babala + pagbawas ng mga araw ng kawalan.",
    consequenceUr: "پہلی تنبیہ + غیر حاضری دنوں کی کٹوتی۔",
    severity: "medium",
  },
  {
    id: "absence_repeated",
    ar: "تكرار الغياب بدون عذر", en: "Repeated unexcused absence",
    hi: "बार-बार बिना बहाने अनुपस्थिति", ne: "दोहोरिएको बिना बहानाको अनुपस्थिति", bn: "বারবার কারণ ছাড়া অনুপস্থিতি", fil: "Paulit-ulit na hindi pinapayagang kawalan", ur: "بار بار بغیر وجہ غیر حاضری",
    articleAr: "المادة 80/4 — يجوز لصاحب العمل فسخ العقد دون مكافأة إذا تكرر الغياب رغم إنذارين متتاليين.",
    articleEn: "Article 80(4) — the employer may terminate without gratuity if absence is repeated despite two consecutive warnings.",
    articleHi: "अनुच्छेद 80(4) — यदि दो क्रमागत चेतावनियों के बावजूद अनुपस्थिति दोहराई जाए तो नियोक्ता बिना ग्रैच्युइटी समाप्त कर सकता है।",
    articleNe: "धारा ८०(४) — दुई क्रमागत चेतावनीपछि पनि अनुपस्थिति दोहोरिएमा नियोक्ताले ग्रेच्युइटी बिना समाप्त गर्न सक्छ।",
    articleBn: "ধারা ৮০(৪) — দুটি ধারাবাহিক সতর্কতা সত্ত্বেও অনুপস্থিতি পুনরাবৃত্তি হলে নিয়োগকর্তা গ্র্যাচুইটি ছাড়াই সমাপ্ত করতে পারে।",
    articleFil: "Artikulo 80(4) — maaaring wakasan ng employer nang walang gratuity kung paulit-ulit ang kawalan sa kabila ng dalawang magkakasunod na babala.",
    articleUr: "مادہ 80(4) — اگر دو مسلسل تنبیہات کے باوجود غیر حاضری دہرائی جائے تو ملازمت دہندہ بغیر گریجوایٹی ختم کر سکتا ہے۔",
    consequenceAr: "إنذار ثانٍ ثم ثالث، يفضي إلى الفصل عند التكرار.",
    consequenceEn: "Second then third warning, leading to termination on recurrence.",
    consequenceHi: "दूसरी फिर तीसरी चेतावनी, दोहराव पर समाप्ति।",
    consequenceNe: "दोस्रो र तेस्रो चेतावनी, दोहोरिएमा समाप्ति।",
    consequenceBn: "দ্বিতীয় তৃতীয় সতর্কতা, পুনরাবৃত্তিতে সমাপ্তি।",
    consequenceFil: "Pangalawa pagkatapos ay pangatlong babala, na humahantong sa pagwawakas.",
    consequenceUr: "دوسری پھر تیسری تنبیہ، دہرانے پر ختم۔",
    severity: "high",
  },
  {
    id: "absence_long",
    ar: "الغياب أكثر من 7 أيام متصلة / 30 يوماً متفرقة", en: "Absence >7 consecutive / 30 separate days",
    hi: "7 दिन लगातार / 30 अलग-अलग दिन से अधिक अनुपस्थिति", ne: "७ दिन लगातार / ३० छुट्टा-छुट्टी दिनभन्दा बढी अनुपस्थिति", bn: "7 দিন একাধারে / 30 পৃথক দিনের বেশি অনুপস্থিতি", fil: "Kawalan na >7 magkakasunod / 30 hiwalay na araw", ur: "7 مسلسل / 30 الگ الگ دن سے زیادہ غیر حاضری",
    articleAr: "المادة 80/2 — انتهاء عقد العمل دون تعويض أو مكافأة إذا غاب العامل أكثر من 30 يوماً متفرقة أو أكثر من 15 يوماً متصلة في السنة.",
    articleEn: "Article 80(2) — contract ends without compensation if the worker is absent more than 30 separate days or more than 15 consecutive days per year.",
    articleHi: "अनुच्छेद 80(2) — यदि कर्मचारी वर्ष में 30 अलग-अलग दिन या 15 लगातार दिन से अधिक अनुपस्थित रहे तो बिना क्षतिपूर्ति समाप्ति।",
    articleNe: "धारा ८०(२) — वर्षमा ३० छुट्टा-छुट्टी दिन वा १५ लगातार दिनभन्दा बढी अनुपस्थित भएमा बिना क्षतिपूर्ति समाप्ति।",
    articleBn: "ধারা ৮০(২) — বছরে ৩০ পৃথক দিন বা ১৫ একাধারে দিনের বেশি অনুপস্থিত হলে ক্ষতিপূরণ ছাড়াই সমাপ্তি।",
    articleFil: "Artikulo 80(2) — nagwawakas nang walang kabayaran kung ang empleyado ay wala nang higit sa 30 hiwalay na araw o 15 magkakasunod na araw bawat taon.",
    articleUr: "مادہ 80(2) — سال میں 30 الگ الگ دن یا 15 مسلسل دن سے زیادہ غیر حاضر رہنے پر بغیر معاوضہ ختم۔",
    consequenceAr: "فسخ العقد (فصل) مباشرة.",
    consequenceEn: "Immediate contract termination.",
    consequenceHi: "तुरंत अनुबंध समाप्ति।",
    consequenceNe: "तुरुन्तै सम्झौता समाप्ति।",
    consequenceBn: "অবিলম্বে চুক্তি সমাপ্তি।",
    consequenceFil: "Dagdagang pagwakas ng kontrata.",
    consequenceUr: "فوری معاہدہ ختم۔",
    severity: "termination",
  },
  {
    id: "tardiness",
    ar: "التأخر المتكرر عن الدوام", en: "Repeated tardiness",
    hi: "बार-बार देर से आना", ne: "दोहोरिएको ढिलो हुनु", bn: "বারবার দেরি করে আসা", fil: "Paulit-ulit na pagkahuli", ur: "بار بار دیر سے آنا",
    articleAr: "لائحة تنظيم العمل الداخلية — الالتزام بمواعيد الدوام (وفق المادة 41).",
    articleEn: "Internal work regulations — adherence to working hours (per Article 41).",
    articleHi: "आंतरिक कार्य नियम — कार्य समय का पालन (अनुच्छेद 41 अनुसार)।",
    articleNe: "आन्तरिक कार्य नियमावली — कार्य समयको पालना (धारा ४१ अनुसार)।",
    articleBn: "অভ্যন্তরীণ কার্য প্রবিধান — কার্যঘণ্টা মেনে চলা (ধারা ৪১ অনুযায়ী)।",
    articleFil: "Panloob na mga regulasyon — pagsunod sa oras ng trabaho (ayon sa Artikulo 41).",
    articleUr: "داخلی کام کے ضوابط — کام کے اوقات کی پابندی (مادہ 41 کے مطابق)۔",
    consequenceAr: "إنذار تصاعدي حسب التكرار.",
    consequenceEn: "Progressive warning per recurrence.",
    consequenceHi: "दोहराव अनुसार बढ़ती चेतावनी।",
    consequenceNe: "दोहोरिएअनुसार बढ्दो चेतावनी।",
    consequenceBn: "পুনরাবৃত্তি অনুযায়ী ক্রমবর্ধমান সতর্কতা।",
    consequenceFil: "Unang babala ayon sa pag-uulit.",
    consequenceUr: "دہرانے کے مطابق بڑھتی تنبیہ۔",
    severity: "medium",
  },
  {
    id: "sleeping",
    ar: "النوم أثناء ساعات العمل", en: "Sleeping during working hours",
    hi: "कार्य घंटों में सोना", ne: "कार्य घण्टामा सुत्नु", bn: "কার্যঘণ্টায় ঘুমানো", fil: "Pagtulog sa oras ng trabaho", ur: "کام کے اوقات میں сонانا",
    articleAr: "المادة 41 — واجبات العامل والالتزام بالتعليمات وأداء العمل بعناية.",
    articleEn: "Article 41 — worker obligations and adherence to instructions and performing work with care.",
    articleHi: "अनुच्छेद 41 — कर्मचारी कर्तव्य और निर्देशों का पालन तथा सावधानी से कार्य।",
    articleNe: "धारा ४१ — कर्मचारी दायित्व र निर्देशन पालना तथा सावधानीपूर्वक कार्य।",
    articleBn: "ধারা ৪১ — কর্মচারীর দায়িত্ব ও নির্দেশ মেনে সাবধানে কাজ করা।",
    articleFil: "Artikulo 41 — mga tungkulin ng empleyado at pagsunod sa mga tagubilin at paggawa ng trabaho nang may pag-iingat.",
    articleUr: "مادہ 41 — ملازم کی ذمہ داریاں اور احکامات کی پابندی اور احتیاط سے کام۔",
    consequenceAr: "إنذار أول، يتصاعد مع التكرار.",
    consequenceEn: "First warning, escalates with recurrence.",
    consequenceHi: "पहली चेतावनी, दोहराव पर बढ़ती है।",
    consequenceNe: "पहिलो चेतावनी, दोहरिएमा बढ्छ।",
    consequenceBn: "প্রথম সতর্কতা, পুনরাবৃত্তিতে বাড়ে।",
    consequenceFil: "Unang babala, lumalala sa pag-uulit.",
    consequenceUr: "پہلی تنبیہ، دہرانے پر بڑھتی ہے۔",
    severity: "medium",
  },
  {
    id: "product_damage",
    ar: "إتلاف/تلف منتجات أو ممتلكات العمل", en: "Damage to products or company property",
    hi: "उत्पादों या कंपनी संपत्ति को नुकसान", ne: "उत्पादन वा कम्पनी सम्पत्तिमा क्षति", bn: "পণ্য বা কোম্পানির সম্পত্তির ক্ষতি", fil: "Pinsala sa produkto o ari-arian ng kumpanya", ur: "مصنوعات یا کمپنی کی املاک کو نقصان",
    articleAr: "المادة 77 و80/6 — التعويض عن الضرر والفسخ عند العمد أو الإهمال الجسيم.",
    articleEn: "Article 77 and 80(6) — compensation for damage and termination on intent or gross negligence.",
    articleHi: "अनुच्छेद 77 और 80(6) — क्षति का क्षतिपूर्ति और जानबूझकर या गंभीर लापरवाही पर समाप्ति।",
    articleNe: "धारा ७७ र ८०(६) — क्षतिको क्षतिपूर्ति र जानबूझकर वा गम्भीर लापरवाहीमा समाप्ति।",
    articleBn: "ধারা ৭৭ ও ৮০(৬) — ক্ষতির ক্ষতিপূরণ এবং ইচ্ছাকৃত বা গুরুতর অবহেলায় সমাপ্তি।",
    articleFil: "Artikulo 77 at 80(6) — kabayaran sa pinsala at pagwakas sa layunin o matinding kapabayaan.",
    articleUr: "مادہ 77 اور 80(6) — نقصان کا معاوضہ اور جان بوجھ کر یا سنگین لاپروائی پر ختم۔",
    consequenceAr: "إنذار/فصل + التعويض عن التلف.",
    consequenceEn: "Warning/termination + compensation for damage.",
    consequenceHi: "चेतावनी/समाप्ति + क्षति का क्षतिपूर्ति।",
    consequenceNe: "चेतावनी/समाप्ति + क्षतिको क्षतिपूर्ति।",
    consequenceBn: "সতর্কতা/সমাপ্তি + ক্ষতির ক্ষতিপূরণ।",
    consequenceFil: "Babala/pagwakas + kabayaran sa pinsala.",
    consequenceUr: "تنبیہ/ختم + نقصان کا معاوضہ۔",
    severity: "high",
  },
  {
    id: "disobedience",
    ar: "عدم تنفيذ الأوامر أو مخالفة التعليمات", en: "Failure to follow lawful orders",
    hi: "वैध आदेशों का पालन न करना", ne: "कानूनी आदेश पालन नगर्नु", bn: "বৈধ আদেশ অমান্য করা", fil: "Pagkabigong sumunod sa mga batayang utos", ur: "جائز احکامات کی نافرمانی",
    articleAr: "المادة 41 — الالتزام بأوامر صاحب العمل المشروعة وأداء العمل وفق التعليمات.",
    articleEn: "Article 41 — compliance with lawful employer orders and performing work per instructions.",
    articleHi: "अनुच्छेद 41 — वैध नियोक्ता आदेशों का पालन और निर्देशानुसार कार्य।",
    articleNe: "धारा ४१ — वैध नियोक्ता आदेश पालन र निर्देशनअनुसार कार्य।",
    articleBn: "ধারা ৪১ — বৈধ নিয়োগকর্তা আদেশ মেনে নির্দেশ অনুযায়ী কাজ।",
    articleFil: "Artikulo 41 — pagsunod sa mga batayang utos ng employer at paggawa ayon sa mga tagubilin.",
    articleUr: "مادہ 41 — جائز ملازمت دہندہ احکامات کی پابندی اور ہدایات کے مطابق کام۔",
    consequenceAr: "إنذار تصاعدي.",
    consequenceEn: "Progressive warning.",
    consequenceHi: "बढ़ती चेतावनी।",
    consequenceNe: "बढ्दो चेतावनी।",
    consequenceBn: "ক্রমবর্ধমান সতর্কতা।",
    consequenceFil: "Unang babala.",
    consequenceUr: "بڑھتی تنبیہ۔",
    severity: "medium",
  },
  {
    id: "disclosure",
    ar: "إفشاء أسرار العمل", en: "Disclosing work secrets",
    hi: "कार्य रहस्य प्रकट करना", ne: "कार्य रहस्य खुलाउनु", bn: "কাজের গোপনীয়তা ফাঁস", fil: "Pagbuhos ng lihim ng trabaho", ur: "کام کے راز افشا کرنا",
    articleAr: "المادة 41 و80/5 — واجب المحافظة على أسرار العمل والفسخ عند الإخلال.",
    articleEn: "Article 41 and 80(5) — duty to preserve work secrets and termination on breach.",
    articleHi: "अनुच्छेद 41 और 80(5) — कार्य रहस्य सुरक्षित रखने का कर्तव्य और उल्लंघन पर समाप्ति।",
    articleNe: "धारा ४१ र ८०(५) — कार्य रहस्य सुरक्षित राख्ने कर्तव्य र उल्लंघनमा समाप्ति।",
    articleBn: "ধারা ৪১ ও ৮০(৫) — কাজের গোপনীয়তা সুরক্ষা কর্তব্য এবং লঙ্ঘনে সমাপ্তি।",
    articleFil: "Artikulo 41 at 80(5) — tungkuling panatilihin ang lihim ng trabaho at pagwakas sa paglabag.",
    articleUr: "مادہ 41 اور 80(5) — کام کے راز محفوظ رکھنے کی ذمہ داری اور خلاف ورزی پر ختم۔",
    consequenceAr: "إنذار/فصل حسب جسامة الإخلال.",
    consequenceEn: "Warning/termination per severity of breach.",
    consequenceHi: "उल्लंघन की गंभीरता अनुसार चेतावनी/समाप्ति।",
    consequenceNe: "उल्लंघनको गम्भीरताअनुसार चेतावनी/समाप्ति।",
    consequenceBn: "লঙ্ঘনের গুরুত্ব অনুযায়ী সতর্কতা/সমাপ্তি।",
    consequenceFil: "Babala/pagwakas ayon sa bigat ng paglabag.",
    consequenceUr: "خلاف ورزی کی سنگینی کے مطابق تنبیہ/ختم۔",
    severity: "high",
  },
  {
    id: "assault",
    ar: "الاعتداء على مدير أو زميل عمل", en: "Assault on a manager or colleague",
    hi: "प्रबंधक या सहकर्मी पर हमला", ne: "प्रबन्धक वा सहकर्मीमाथि आक्रमण", bn: "ব্যবস্থাপক বা সহকর্মীর ওপর আক্রমণ", fil: "Pagsalakay sa manager o katrabaho", ur: "مینیجر یا ساتھی کارکن پر حملہ",
    articleAr: "المادة 80/7 — الفسخ دون مكافأة إذا ارتكب العامل اعتداءً على صاحب العمل أو مديره أو رئيسه.",
    articleEn: "Article 80(7) — termination without gratuity if the worker assaults the employer, manager, or supervisor.",
    articleHi: "अनुच्छेद 80(7) — यदि कर्मचारी नियोक्ता, प्रबंधक या सुपरवाइज़र पर हमला करे तो बिना ग्रैच्युइटी समाप्ति।",
    articleNe: "धारा ८०(७) — कर्मचारीले नियोक्ता, प्रबन्धक वा सुपरिव्यक्तामाथि आक्रमण गरेमा ग्रेच्युइटी बिना समाप्ति।",
    articleBn: "ধারা ৮০(৭) — কর্মচারী নিয়োগকর্তা, ব্যবস্থাপক বা সুপারভাইজারকে আক্রমণ করলে গ্র্যাচুইটি ছাড়াই সমাপ্তি।",
    articleFil: "Artikulo 80(7) — pagwakas nang walang gratuity kung salakayin ng empleyado ang employer, manager, o supervisor.",
    articleUr: "مادہ 80(7) — اگر ملازم ملازمت دہندہ، مینیجر یا نگران پر حملہ کرے تو بغیر گریجوایٹی ختم۔",
    consequenceAr: "فسخ العقد (فصل).",
    consequenceEn: "Contract termination.",
    consequenceHi: "अनुबंध समाप्ति।",
    consequenceNe: "सम्झौता समाप्ति।",
    consequenceBn: "চুক্তি সমাপ্তি।",
    consequenceFil: "Pagwakas ng kontrata.",
    consequenceUr: "معاہدہ ختم۔",
    severity: "termination",
  },
  {
    id: "safety",
    ar: "مخالفة قواعد السلامة والصحة المهنية", en: "Occupational safety violation",
    hi: "व्यावसायिक सुरक्षा उल्लंघन", ne: "व्यावसायिक सुरक्षा उल्लंघन", bn: "পেশাগত নিরাপত্তা লঙ্ঘন", fil: "Paglabag sa kaligtasan sa trabaho", ur: "پیشہ ورانہ حفاظت کی خلاف ورزی",
    articleAr: "المادة 41 ونظام السلامة — واجب الالتزام بتعليمات الوقاية والسلامة.",
    articleEn: "Article 41 and safety regulations — duty to follow prevention and safety instructions.",
    articleHi: "अनुच्छेद 41 और सुरक्षा नियम — रोकथाम एवं सुरक्षा निर्देशों का पालन कर्तव्य।",
    articleNe: "धारा ४१ र सुरक्षा नियम — रोकथाम र सुरक्षा निर्देशन पालना कर्तव्य।",
    articleBn: "ধারা ৪১ ও নিরাপত্তা বিধি — প্রতিরোধ ও নিরাপত্তা নির্দেশ মেনে চলা কর্তব্য।",
    articleFil: "Artikulo 41 at mga regulasyon ng kaligtasan — tungkuling sundin ang mga tagubilin sa pag-iwas at kaligtasan.",
    articleUr: "مادہ 41 اور حفاظتی ضوابط — روک تھام اور حفاظتی احکامات کی پابندی کی ذمہ داری۔",
    consequenceAr: "إنذار تصاعدي، قد يفضي للفصل.",
    consequenceEn: "Progressive warning, may lead to termination.",
    consequenceHi: "बढ़ती चेतावनी, समाप्ति तक जा सकती है।",
    consequenceNe: "बढ्दो चेतावनी, समाप्तिसम्म जान सक्छ।",
    consequenceBn: "ক্রমবর্ধমান সতর্কতা, সমাপ্তি পর্যন্ত যেতে পারে।",
    consequenceFil: "Unang babala, maaaring magwakas.",
    consequenceUr: "بڑھتی تنبیہ، ختم تک جا سکتی ہے۔",
    severity: "medium",
  },
  {
    id: "other",
    ar: "مخالفة أخرى وفق لائحة تنظيم العمل", en: "Other violation per internal regulations",
    hi: "आंतरिक नियम अनुसार अन्य उल्लंघन", ne: "आन्तरिक नियमअनुसार अन्य उल्लंघन", bn: "অভ্যন্তরীণ প্রবিধান অনুযায়ী অন্য লঙ্ঘন", fil: "Iba pang paglabag ayon sa panloob na regulasyon", ur: "داخلی ضوابط کے مطابق دیگر خلاف ورزی",
    articleAr: "لائحة تنظيم العمل الداخلية المعتمدة لدى مكتب العمل.",
    articleEn: "Internal work regulations registered with the Labor Office.",
    articleHi: "श्रम कार्यालय में पंजीकृत आंतरिक कार्य नियम।",
    articleNe: "श्रम कार्यालयमा दर्ता आन्तरिक कार्य नियमावली।",
    articleBn: "শ্রম দপ্তরে নিবন্ধিত অভ্যন্তরীণ কার্য প্রবিধান।",
    articleFil: "Panloob na regulasyon ng trabaho na nakarehistro sa Labor Office.",
    articleUr: "محکمه محکمہ مزدور شعبہ میں رجسٹرڈ داخلے ضوابط۔",
    consequenceAr: "حسب قواعد الائحة.",
    consequenceEn: "Per internal regulations.",
    consequenceHi: "आंतरिक नियम अनुसार।",
    consequenceNe: "आन्तरिक नियमअनुसार।",
    consequenceBn: "অভ্যন্তরীণ প্রবিধান অনুযায়ী।",
    consequenceFil: "Ayon sa panloob na regulasyon.",
    consequenceUr: "داخلی ضوابط کے مطابق۔",
    severity: "low",
  },
];

export const WARNING_LEVELS = [
  { id: "first", ar: "إنذار أول", en: "First warning", hi: "पहली चेतावनी", ne: "पहिलो चेतावनी", bn: "প্রথম সতর্কতা", fil: "Unang babala", ur: "پہلی تنبیہ", cls: "bg-amber-50 text-amber-700 border-amber-200", sev: "low" },
  { id: "second", ar: "إنذار ثانٍ", en: "Second warning", hi: "दूसरी चेतावनी", ne: "दोस्रो चेतावनी", bn: "দ্বিতীয় সতর্কতা", fil: "Pangalawang babala", ur: "دوسری تنبیہ", cls: "bg-orange-50 text-orange-700 border-orange-200", sev: "medium" },
  { id: "third", ar: "إنذار ثالث (نهائي)", en: "Third (final) warning", hi: "तीसरी (अंतिम) चेतावनी", ne: "तेस्रो (अन्तिम) चेतावनी", bn: "তৃতীয় (চূড়ান্ত) সতর্কতা", fil: "Ikatlong (huling) babala", ur: "تیسری (آخری) تنبیہ", cls: "bg-rose-50 text-rose-700 border-rose-200", sev: "high" },
  { id: "termination", ar: "فسخ العقد (فصل)", en: "Contract termination", hi: "अनुबंध समाप्ति", ne: "सम्झौता समाप्ति", bn: "চুক্তি সমাপ্তি", fil: "Pagwakas ng kontrata", ur: "معاہدہ ختم", cls: "bg-red-600 text-white border-red-700", sev: "termination" },
];

const ORDER = ["first", "second", "third", "termination"];

export function suggestLevel(existingCount, category) {
  if (!category) return "first";
  if (category.severity === "termination") return "termination";
  return ORDER[Math.min(existingCount, ORDER.length - 1)];
}

export function categoryById(id, lang) {
  const c = VIOLATION_CATEGORIES.find((x) => x.id === id);
  if (!c) return null;
  const l = lang || "ar";
  const suf = cap(l);
  return {
    ...c,
    label: c[l] || c.en,
    article: c["article" + suf] || c.articleEn,
    consequence: c["consequence" + suf] || c.consequenceEn,
  };
}

export function levelById(id, lang) {
  const l = WARNING_LEVELS.find((x) => x.id === id) || WARNING_LEVELS[0];
  const lng = lang || "ar";
  return { ...l, label: l[lng] || l.en };
}

export const LABOR_POLICY_INTRO = {
  ar: "تستند سياسة العمل والإنذارات إلى نظام العمل السعودي ولائحة تنظيم العمل الداخلية المعتمدة لدى مكتب العمل. يُصدر الإنذار بعد إجراء جلسة وتحقق من ثبوت المخالفة على الموظف، ويُرسل مباشرة إلى بوابة الموظف الذاتية دون الحاجة لموافقة الموظف — إذ يُعتبر الإنذار نافذاً ومعتمداً بمجرد إرساله، ولا يُحتجج به على الموظف إلا بعد تحقيق واثبات.",
  en: "The labor policy and warnings are based on the Saudi Labor Law and the internal work regulations registered with the Labor Office. A warning is issued after a session is held and the violation against the employee is established; it is sent directly to the employee self-service portal without requiring the employee's approval — the warning is effective upon sending, and cannot be held against the worker without investigation and proof.",
  hi: "श्रम नीति और चेतावनियाँ सऊदी श्रम कानून और श्रम कार्यालय में पंजीकृत आंतरिक कार्य नियमों पर आधारित हैं। चेतावनी एक सत्र आयोजित करने और कर्मचारी पर उल्लंघन सिद्ध करने के बाद जारी की जाती है; इसे कर्मचारी की स्वीकृति की आवश्यकता के बिना सीधे कर्मचारी स्व-सेवा पोर्टल पर भेजा जाता है — चेतावनी भेजते ही प्रभावी है, और जाँच व प्रमाण के बिना इसे कर्मचारी के विरुद्ध नहीं रखा जा सकता।",
  ne: "श्रम नीति र चेतावनीहरू साउदी श्रम कानून र श्रम कार्यालयमा दर्ता आन्तरिक कार्य नियमावलीमा आधारित छन्। एक सत्र बसेर कर्मचारीमाथि उल्लंघन प्रमाणित भएपछि चेतावनी जारी गरिन्छ; यो कर्मचारीको स्वीकृति बिना सिधै कर्मचारी स्व-सेवा पोर्टलमा पठाइन्छ — चेतावनी पठाउनासाथै प्रभावी हुन्छ, र अनुसन्धान र प्रमाण बिना यो कर्मचारीविरुद्ध लागू हुँदैन।",
  bn: "শ্রম নীতি ও সতর্কতাগুলো সৌদি শ্রম আইন এবং শ্রম দপ্তরে নিবন্ধিত অভ্যন্তরীণ কার্য প্রবিধানের উপর ভিত্তি করে। একটি সেশন অনুষ্ঠিত হওয়া এবং কর্মচারীর বিরুদ্ধে লঙ্ঘন প্রমাণিত হওয়ার পর সতর্কতা জারি করা হয়; এটি কর্মচারীর অনুমোদন ছাড়াই সরাসরি কর্মচারী স্ব-সেবা পোর্টালে পাঠানো হয় — সতর্কতা পাঠানোর সাথে সাথেই কার্যকর হয়, এবং তদন্ত ও প্রমাণ ছাড়া এটি কর্মচারীর বিরুদ্ধে ব্যবহার করা যায় না।",
  fil: "Ang labor policy at mga babala ay nakabatay sa Saudi Labor Law at sa panloob na regulasyon ng trabaho na nakarehistro sa Labor Office. Inisyu ang babala pagkatapos ng sesyon at napatunayan ang paglabag laban sa empleyado; ipinapadala nang direkta sa employee self-service portal nang hindi nangangailangan ng pag-apruba — epektibo ang babala sa pagpapadala, at hindi magagamit laban sa empleyado nang walang imbestigasyon at patunay.",
  ur: "مزدور پالیسی اور تنبیہات سعودی مزدور قانون اور محکمه مزدور میں رجسٹرڈ داخلی کام کے ضوابط پر مبنی ہیں۔ ایک نشست منعقد کرنے اور ملازم پر خلاف ورزی ثابت ہونے کے بعد تنبیہ جاری کی جاتی ہے؛ اسے ملازم کی منظوری کے بغیر براہ راست ملازم سلف سروس پورٹل پر بھیجا جاتا ہے — تنبیہ بھیجتے ہی نافذ ہو جاتی ہے، اور تحقیقات اور ثبوت کے بغیر اسے ملازم کے خلاف استعمال نہیں کیا جا سکتا۔",
};