import { buildOrgTree, orgStats, roleLabel, employeeDisplayName } from "@/lib/orgTree";

const ROLE_COLORS = {
  owner: "#d97706",
  executive: "#7c3aed",
  manager: "#2563eb",
  supervisor: "#059669",
  employee: "#475569",
  worker: "#ea580c",
};

// بناء كيانات HTML برمجياً لتجنّب كتابتها حرفياً في المصدر
const AMP = String.fromCharCode(38);
const ENT = {
  amp: AMP + "amp;",
  lt: AMP + "lt;",
  gt: AMP + "gt;",
  quot: AMP + "quot;",
  apos: AMP + "#39;",
  bull: "\u2022",
};

function escapeHtml(s) {
  s = s == null ? "" : String(s);
  return s
    .replace(/&/g, ENT.amp)
    .replace(/</g, ENT.lt)
    .replace(/>/g, ENT.gt)
    .replace(/"/g, ENT.quot)
    .replace(/'/g, ENT.apos);
}

function formatDate(lang) {
  try {
    return new Date().toLocaleDateString(lang === "ar" ? "ar-SA" : "en-GB", {
      year: "numeric", month: "long", day: "numeric",
    });
  } catch {
    return new Date().toISOString().slice(0, 10);
  }
}

function renderNode(node, lang, depth) {
  const color = ROLE_COLORS[node.role_level] || ROLE_COLORS.employee;
  const name = escapeHtml(employeeDisplayName(node));
  const role = escapeHtml(roleLabel(node.role_level, lang));
  const subParts = [];
  if (node.position && node.position !== node.full_name) subParts.push(node.position);
  if (node.department) subParts.push(node.department);
  if (node.employee_number) subParts.push("#" + node.employee_number);
  const sub = subParts.map(escapeHtml).join(" " + ENT.bull + " ");
  const kids = node._children || [];
  const pad = depth * 22;
  const kidsHtml = kids.map(function (k) { return renderNode(k, lang, depth + 1); }).join("");
  return (
    "<div style=\"margin:6px 0 6px " + pad + "px;padding:8px 10px;border-inline-start:3px solid " + color + ";background:#f8fafc;border-radius:6px;\">" +
      "<div style=\"display:flex;align-items:center;gap:8px;flex-wrap:wrap;\">" +
        "<span style=\"display:inline-block;width:9px;height:9px;border-radius:50%;background:" + color + ";\"></span>" +
        "<span style=\"font-size:11px;color:" + color + ";font-weight:700;\">" + role + "</span>" +
        "<span style=\"font-size:14px;font-weight:700;color:#0f172a;\">" + name + "</span>" +
      "</div>" +
      (sub ? "<div style=\"font-size:11px;color:#64748b;margin-top:2px;margin-inline-start:17px;\">" + sub + "</div>" : "") +
    "</div>" + kidsHtml
  );
}

export function buildOrgHTML(_ref) {
  const employees = _ref.employees || [];
  const lang = _ref.lang || "ar";
  const orgName = _ref.orgName || "";
  const logoUrl = _ref.logoUrl || "";
  const isAr = lang === "ar";
  const tree = buildOrgTree(employees);
  const stats = orgStats(employees);
  const orphans = employees.filter(function (e) { return !e.manager_id && e.role_level !== "owner" && e.role_level !== "executive"; });
  const title = isAr ? "الهيكل التنظيمي" : "Organizational Structure";
  const dateL = isAr ? "تاريخ الإصدار" : "Issue date";
  const statsRows = isAr
    ? [["إجمالي القوى العاملة", stats.total], ["عدد الإدارات", stats.departments.length],
       ["المدراء", stats.byLevel.manager + stats.byLevel.executive + stats.byLevel.owner],
       ["المشرفون", stats.byLevel.supervisor]]
    : [["Total workforce", stats.total], ["Departments", stats.departments.length],
       ["Managers", stats.byLevel.manager + stats.byLevel.executive + stats.byLevel.owner],
       ["Supervisors", stats.byLevel.supervisor]];
  const orphansL = isAr ? "موظفون بدون مدير مباشر" : "Employees without direct manager";

  const statsCells = statsRows.map(function (r) {
    return "<td style=\"border:1px solid #e2e8f0;padding:8px 12px;text-align:center;width:25%;\">" +
      "<div style=\"font-size:20px;font-weight:700;color:#7c3aed;\">" + r[1] + "</div>" +
      "<div style=\"font-size:11px;color:#64748b;margin-top:2px;\">" + escapeHtml(r[0]) + "</div>" +
    "</td>";
  }).join("");

  const treeHtml = tree.map(function (n) { return renderNode(n, lang, 0); }).join("");
  const orphansHtml = orphans.length
    ? ("<div style=\"margin-top:24px;\">" +
         "<div style=\"font-size:13px;font-weight:700;color:#475569;margin-bottom:8px;\">" + orphansL + " (" + orphans.length + ")</div>" +
         orphans.map(function (e) {
           return "<span style=\"display:inline-block;font-size:11px;padding:4px 10px;margin:3px;border:1px solid #e2e8f0;border-radius:6px;background:#f8fafc;\">" + escapeHtml(employeeDisplayName(e)) + "</span>";
         }).join(" ") +
       "</div>")
    : "";

  const logo = logoUrl
    ? "<img src=\"" + escapeHtml(logoUrl) + "\" style=\"height:54px;max-width:160px;object-fit:contain;\" />"
    : "";
  const brand = isAr ? "جدارة" : "Jadara HR";
  const foot = isAr ? "تم إنشاء هذا المستند عبر نظام جدارة للموارد البشرية" : "Generated by Jadara HR System";

  return "<!DOCTYPE html>" +
    "<html xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" xmlns=\"http://www.w3.org/TR/REC-html40\" dir=\"rtl\" lang=\"" + (isAr ? "ar" : "en") + "\">" +
    "<head><meta charset=\"utf-8\" /><title>" + escapeHtml(title) + "</title>" +
    "<style>" +
      "@page { size: A4; margin: 14mm; }" +
      "body { font-family: 'Tajawal','IBM Plex Sans Arabic','Arial',sans-serif; color:#0f172a; margin:0; }" +
      ".doc { max-width:780px; margin:0 auto; }" +
      ".head { display:flex; align-items:center; justify-content:space-between; gap:16px; padding-bottom:14px; border-bottom:2px solid #7c3aed; margin-bottom:16px; }" +
      ".head h1 { font-size:20px; margin:0; }" +
      ".head .sub { font-size:11px; color:#64748b; margin-top:4px; }" +
      ".brand { font-size:11px; color:#94a3b8; }" +
      ".stats { width:100%; border-collapse:collapse; margin:14px 0 18px; }" +
      ".foot { margin-top:28px; padding-top:10px; border-top:1px solid #e2e8f0; font-size:10px; color:#94a3b8; text-align:center; }" +
      "@media print { body { print-color-adjust:exact; -webkit-print-color-adjust:exact; } }" +
    "</style></head><body>" +
    "<div class=\"doc\">" +
      "<div class=\"head\">" +
        "<div>" +
          (orgName ? "<div style=\"font-size:13px;font-weight:700;color:#7c3aed;\">" + escapeHtml(orgName) + "</div>" : "") +
          "<h1>" + escapeHtml(title) + "</h1>" +
          "<div class=\"sub\">" + escapeHtml(dateL) + ": " + escapeHtml(formatDate(lang)) + "</div>" +
        "</div>" +
        "<div style=\"text-align:center;\">" + logo + "<div class=\"brand\" style=\"margin-top:6px;\">" + brand + "</div></div>" +
      "</div>" +
      "<table class=\"stats\"><tr>" + statsCells + "</tr></table>" +
      treeHtml +
      orphansHtml +
      "<div class=\"foot\">" + foot + "</div>" +
    "</div></body></html>";
}

export function printOrgChartPDF(opts) {
  const html = buildOrgHTML(opts);
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(function () { try { w.print(); } catch (e) {} }, 500);
}

export function downloadOrgWord(opts) {
  const html = buildOrgHTML(opts);
  const blob = new Blob(["\ufeff", html], { type: "application/msword;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "org-chart.doc";
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(function () { URL.revokeObjectURL(url); }, 1500);
}