import React, { useEffect, useState, useMemo } from "react";
import { base44 } from "@/api/base44Client";
import ReactMarkdown from "react-markdown";
import { Crown } from "lucide-react";
import { fetchOrg, preloadLogo } from "@/lib/printBrand";

// مستند البطاقة الوظيفية — يُستخدم للطباعة PDF لكل وظيفة (شاغرة / مغلقة / منتهية).
// الترويسة: شعار المنشأة أعلى اليمين، وشعار جداره أعلى اليسار.
// المحتوى (المؤهلات / المهام / الوصف) يُعرض كـ Markdown مُنسّق بدلاً من نص خام.
export default function JobCardDoc({ job, isAr = true, org: orgProp }) {
  const [orgState, setOrgState] = useState(orgProp || null);

  useEffect(() => {
    if (orgProp) { setOrgState(orgProp); preloadLogo(orgProp?.logo_url); return; }
    let alive = true;
    fetchOrg().then((o) => { if (alive) { setOrgState(o); preloadLogo(o?.logo_url); } }).catch(() => {});
    return () => { alive = false; };
  }, [orgProp]);

  const org = orgProp || orgState;

  const t = isAr ? {
    card: "البطاقة الوظيفية", status: "الحالة", prof: "المهنة", type: "نوع الوظيفة",
    grade: "الدرجة الوظيفية", salary: "الراتب", vac: "عدد الشواغر", dept: "الإدارة",
    natReq: "المطلوب", qual: "المؤهلات المطلوبة", tasks: "المهام والمسؤوليات",
    desc: "الوصف الوظيفي", published: "تاريخ النشر", closed: "تاريخ الإغلاق",
    hired: "الموظف المعيّن", open: "شاغرة", closedB: "مغلقة",
    fullTime: "دوام كامل", partTime: "دوام جزئي", contract: "عقد", sar: "ريال",
    natAny: "الجميع", natSaudi: "سعودي", natResident: "مقيم", na: "—",
    platform: "منصة الموارد البشرية", footer: "تم إنشاء هذه البطاقة عبر نظام جداره للموارد البشرية",
  } : {
    card: "Job Card", status: "Status", prof: "Profession", type: "Type",
    grade: "Grade", salary: "Salary", vac: "Vacancies", dept: "Department",
    natReq: "Required", qual: "Qualifications", tasks: "Tasks & responsibilities",
    desc: "Job description", published: "Published", closed: "Closed",
    hired: "Hired employee", open: "Open", closedB: "Closed",
    fullTime: "Full-time", partTime: "Part-time", contract: "Contract", sar: "SAR",
    natAny: "Any", natSaudi: "Saudi", natResident: "Resident", na: "—",
    platform: "HR Platform", footer: "Generated by Jadara HR System",
  };

  const typeLabel = job.job_type === "full_time" ? t.fullTime : job.job_type === "part_time" ? t.partTime : t.contract;
  const natLabel = { any: t.natAny, saudi: t.natSaudi, resident: t.natResident }[job.nationality_req] || job.nationality_req || t.na;
  const statusLabel = job.status === "open" ? t.open : t.closedB;
  const statusBg = job.status === "open" ? "#dcfce7" : "#e5e7eb";
  const statusFg = job.status === "open" ? "#166534" : "#374151";

  // تقسيم الحقول الطويلة إلى مقاطع لا تُكسر بين الصفحات (عند --- أو العناوين).
  const sections = useMemo((field) => null, []);
  const splitSections = (raw) => {
    const s = String(raw || "").replace(/\r/g, "");
    if (!s.trim()) return [];
    return s
      .split(/(?:^|\n)\s*---\s*(?:\n|$)/)
      .map((x) => x.trim())
      .filter(Boolean)
      .flatMap((x) => {
        const parts = x.split(/(\n(?:#{1,4})\s+[^\n]+)/g).filter((p) => p && p.trim());
        const out = [];
        let buf = "";
        for (const p of parts) {
          const isHead = /^\n?#{1,4}\s+/.test(p);
          if (isHead) { if (buf.trim()) out.push(buf.trim()); buf = p; }
          else buf += p;
        }
        if (buf.trim()) out.push(buf.trim());
        return out.length ? out : [x];
      });
  };

  const Field = ({ label, value }) =>
    value ? (
      <div className="jc-section" style={{ breakInside: "avoid", pageBreakInside: "avoid", marginBottom: 14 }}>
        <div style={{ fontSize: 12, fontWeight: 800, color: "#6d28d9", marginBottom: 5, borderInlineStart: "3px solid #6d28d9", paddingInlineStart: 8 }}>
          {label}
        </div>
        <div className="jc-md" style={{ fontSize: 12.5, lineHeight: 1.95 }}>
          {splitSections(value).length
            ? splitSections(value).map((sec, i) => (
                <div key={i} className="jc-block" style={{ breakInside: "avoid", pageBreakInside: "avoid", marginBottom: 8 }}>
                  <ReactMarkdown>{sec}</ReactMarkdown>
                </div>
              ))
            : <ReactMarkdown>{value}</ReactMarkdown>}
        </div>
      </div>
    ) : null;

  return (
    <div style={{ fontFamily: "'Tajawal','IBM Plex Sans Arabic',sans-serif", color: "#0f172a", maxWidth: 800, margin: "0 auto" }} dir={isAr ? "rtl" : "ltr"}>
      {/* الترويسة: شعار المنشأة يميناً + شعار جداره يساراً */}
      <div className="jc-header" style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", borderBottom: "2px solid #0b1120", paddingBottom: 12, marginBottom: 16, breakInside: "avoid", pageBreakInside: "avoid" }}>
        <div style={{ display: "flex", flexDirection: "column", alignItems: isAr ? "flex-end" : "flex-start", maxWidth: 260 }}>
          {org?.logo_url
            ? <img src={org.logo_url} crossOrigin="anonymous" alt="" style={{ maxWidth: 150, maxHeight: 60, objectFit: "contain" }} />
            : null}
          <div style={{ fontWeight: 700, fontSize: 13, color: "#0b1120", marginTop: 6, textAlign: isAr ? "right" : "left" }}>{org?.name || t.na}</div>
          {org?.unified_number ? <div style={{ fontSize: 10, color: "#666" }}>{isAr ? "الرقم الموحد: " : "Unified No: "}{org.unified_number}</div> : null}
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div style={{ width: 44, height: 44, borderRadius: 14, background: "#2d234a", boxShadow: "0 0 0 1px rgba(197,160,89,.35)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
            <Crown size={22} strokeWidth={1.8} style={{ color: "#c5a059" }} />
          </div>
          <div style={{ display: "flex", flexDirection: "column" }}>
            <div style={{ fontWeight: 800, fontSize: 15, color: "#1a1a2e" }}>جداره</div>
            <div style={{ fontSize: 10, color: "#1a1a2e", marginTop: 1, opacity: 0.75 }}>{t.platform}</div>
          </div>
        </div>
      </div>

      {/* عنوان البطاقة */}
      <div className="jc-title-block" style={{ breakInside: "avoid", pageBreakInside: "avoid", marginBottom: 14 }}>
        <h1 style={{ fontSize: 19, fontWeight: 800, margin: "0 0 4px" }}>{t.card}: {job.title}</h1>
        <span style={{ display: "inline-block", fontSize: 11, padding: "4px 12px", borderRadius: 9999, fontWeight: 700, background: statusBg, color: statusFg }}>{statusLabel}</span>
      </div>

      {/* جدول البيانات الأساسية */}
      <table className="jc-meta" style={{ width: "100%", borderCollapse: "collapse", marginBottom: 14, breakInside: "avoid", pageBreakInside: "avoid" }}>
        <tbody>
          <Meta k={t.status} v={statusLabel} />
          <Meta k={t.prof} v={job.profession || t.na} />
          <Meta k={t.type} v={typeLabel} />
          <Meta k={t.grade} v={job.grade || t.na} />
          <Meta k={t.salary} v={job.salary ? `${job.salary} ${t.sar}` : t.na} />
          <Meta k={t.vac} v={String(Number(job.vacancy_count) || 1)} />
          <Meta k={t.dept} v={job.department || t.na} />
          <Meta k={t.natReq} v={natLabel} />
          {job.published_date ? <Meta k={t.published} v={job.published_date} /> : null}
          {job.closed_date ? <Meta k={t.closed} v={job.closed_date} /> : null}
          {job.hired_applicant_name ? <Meta k={t.hired} v={job.hired_applicant_name} /> : null}
        </tbody>
      </table>

      <Field label={t.qual} value={job.qualifications} />
      <Field label={t.tasks} value={job.tasks} />
      <Field label={t.desc} value={job.description} />

      <div style={{ marginTop: 24, paddingTop: 8, borderTop: "1px solid #e2e8f0", fontSize: 10, color: "#94a3b8", textAlign: "center" }}>{t.footer}</div>
    </div>
  );
}

function Meta({ k, v }) {
  return (
    <tr>
      <td style={{ background: "#f8fafc", fontWeight: 700, color: "#475569", fontSize: 11, padding: "6px 10px", width: "38%", border: "1px solid #e2e8f0" }}>{k}</td>
      <td style={{ fontSize: 12, padding: "6px 10px", border: "1px solid #e2e8f0" }}>{v}</td>
    </tr>
  );
}