import React from "react";
import { formatCurrency } from "@/lib/hr";
import { TrendingUp, TrendingDown, Wallet, Repeat } from "lucide-react";
import { cn } from "@/lib/utils";

// تقرير العمليات المالية للطباعة/PDF — يلتزم بـ A4 (فئة .print-report) ويعرض
// بطاقات المؤشرات + جدول الفترات وفق طريقة العرض المختارة (شهري/نصف/سنوي...).
export default function FinancePrintReport({ rows, totals, fixed, modeLabel, isAr = true }) {
  const kpis = [
    { icon: TrendingUp, tint: "emerald", label: isAr ? "إجمالي الإيرادات" : "Total revenue", value: formatCurrency(totals.revenue) },
    { icon: TrendingDown, tint: "rose", label: isAr ? "إجمالي المصروفات" : "Total expenses", value: formatCurrency(totals.expense) },
    { icon: Wallet, tint: "navy", label: isAr ? "صافي الإيراد" : "Net profit", value: formatCurrency(totals.net) },
    { icon: Repeat, tint: "amber", label: isAr ? "مصروف ثابت (شهري / سنوي)" : "Fixed (monthly / yearly)", value: `${formatCurrency(fixed.monthly)} / ${formatCurrency(fixed.yearly)}` },
  ];
  return (
    <div className="print-report hidden">
      <header className="flex items-center justify-between border-b border-slate-300 pb-2 mb-4">
        <div>
          <h1 className="text-lg font-bold text-[#0B2545]">{isAr ? "تقرير العمليات المالية" : "Financial Operations Report"}</h1>
          <p className="text-[10px] text-slate-500">{isAr ? "بوابة المالك — جدارة" : "Owner Portal — Jadara"}</p>
        </div>
        <div className="text-[10px] text-slate-600 text-left">
          <div>{isAr ? "طريقة العرض" : "View"}: <b>{modeLabel}</b></div>
          <div>{isAr ? "تاريخ التقرير" : "Date"}: {new Date().toLocaleDateString(isAr ? "ar-SA" : "en-GB")}</div>
        </div>
      </header>

      <div className="grid grid-cols-4 gap-2 mb-4">
        {kpis.map((k, i) => (
          <div key={i} className={cn("rounded-lg border p-2", TINTS[k.tint])}>
            <div className="flex items-center gap-1 text-[8px] font-medium opacity-80"><k.icon size={10} /> {k.label}</div>
            <div className="text-[11px] font-extrabold tabular-nums mt-1">{k.value}</div>
          </div>
        ))}
      </div>

      <table className="w-full text-[9pt] border-collapse">
        <thead className="bg-slate-100 text-slate-600">
          <tr>
            <th className="text-right px-2 py-1.5 border border-slate-200 font-medium">{isAr ? "الفترة" : "Period"}</th>
            <th className="text-right px-2 py-1.5 border border-slate-200 font-medium text-emerald-700">{isAr ? "الإيرادات" : "Revenue"}</th>
            <th className="text-right px-2 py-1.5 border border-slate-200 font-medium text-rose-700">{isAr ? "المصروفات" : "Expenses"}</th>
            <th className="text-right px-2 py-1.5 border border-slate-200 font-medium">{isAr ? "الصافي" : "Net"}</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.start} className={cn(r.revenue === 0 && r.expense === 0 && "opacity-50")}>
              <td className="px-2 py-1.5 border border-slate-200 font-medium">{r.label}</td>
              <td className="px-2 py-1.5 border border-slate-200 tabular-nums text-emerald-700">{formatCurrency(r.revenue)}</td>
              <td className="px-2 py-1.5 border border-slate-200 tabular-nums text-rose-600">{formatCurrency(r.expense)}</td>
              <td className={cn("px-2 py-1.5 border border-slate-200 tabular-nums font-bold", r.net >= 0 ? "text-slate-800" : "text-rose-700")}>{formatCurrency(r.net)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr className="bg-slate-900 text-white font-bold">
            <td className="px-2 py-2 border border-slate-900">{isAr ? "الإجمالي" : "Total"}</td>
            <td className="px-2 py-2 border border-slate-900 tabular-nums">{formatCurrency(totals.revenue)}</td>
            <td className="px-2 py-2 border border-slate-900 tabular-nums">{formatCurrency(totals.expense)}</td>
            <td className="px-2 py-2 border border-slate-900 tabular-nums">{formatCurrency(totals.net)}</td>
          </tr>
        </tfoot>
      </table>

      <p className="text-[8px] text-slate-400 mt-3">{isAr ? "تم توليد هذا التقرير آلياً من نظام جدارة — بوابة المالك." : "Generated by Jadara — Owner Portal."}</p>
    </div>
  );
}

const TINTS = {
  emerald: "bg-emerald-50 text-emerald-700 border-emerald-200",
  rose: "bg-rose-50 text-rose-700 border-rose-200",
  navy: "bg-slate-50 text-[#0B2545] border-[#0B2545]/15",
  amber: "bg-amber-50 text-amber-700 border-amber-200",
};